// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class ConfigLogging: ConfigStub {
    let inner: any ConfigStub
    let logger: Logger

    public init(_ inner: any ConfigStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-config-v1"
      logger[metadataKey: "gcp.client.service"] = "config"
      logger[metadataKey: "gcp.experimental.swift.client"] = "Config"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listDeployments(
      request: ListDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListDeploymentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDeployments",
        action: {
          (r: ListDeploymentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.ListDeploymentsResponse
          in
          return try await self.inner.listDeployments(request: r, options: o)
        })
    }

    public func getDeployment(
      request: GetDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Deployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDeployment",
        action: {
          (r: GetDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.Deployment
          in
          return try await self.inner.getDeployment(request: r, options: o)
        })
    }

    public func createDeployment(
      request: CreateDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDeployment",
        action: {
          (r: CreateDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDeployment(request: r, options: o)
        })
    }

    public func updateDeployment(
      request: UpdateDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDeployment",
        action: {
          (r: UpdateDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDeployment(request: r, options: o)
        })
    }

    public func deleteDeployment(
      request: DeleteDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDeployment",
        action: {
          (r: DeleteDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDeployment(request: r, options: o)
        })
    }

    public func listRevisions(
      request: ListRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListRevisionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRevisions",
        action: {
          (r: ListRevisionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.ListRevisionsResponse
          in
          return try await self.inner.listRevisions(request: r, options: o)
        })
    }

    public func getRevision(
      request: GetRevisionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Revision {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRevision",
        action: {
          (r: GetRevisionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.Revision
          in
          return try await self.inner.getRevision(request: r, options: o)
        })
    }

    public func getResource(
      request: GetResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Resource {
      try await self._intercept(
        request: request,
        options: options,
        name: "getResource",
        action: {
          (r: GetResourceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.Resource
          in
          return try await self.inner.getResource(request: r, options: o)
        })
    }

    public func listResources(
      request: ListResourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListResourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listResources",
        action: {
          (r: ListResourcesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.ListResourcesResponse
          in
          return try await self.inner.listResources(request: r, options: o)
        })
    }

    public func exportDeploymentStatefile(
      request: ExportDeploymentStatefileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Statefile {
      try await self._intercept(
        request: request,
        options: options,
        name: "exportDeploymentStatefile",
        action: {
          (r: ExportDeploymentStatefileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.Statefile
          in
          return try await self.inner.exportDeploymentStatefile(request: r, options: o)
        })
    }

    public func exportRevisionStatefile(
      request: ExportRevisionStatefileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Statefile {
      try await self._intercept(
        request: request,
        options: options,
        name: "exportRevisionStatefile",
        action: {
          (r: ExportRevisionStatefileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.Statefile
          in
          return try await self.inner.exportRevisionStatefile(request: r, options: o)
        })
    }

    public func importStatefile(
      request: ImportStatefileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Statefile {
      try await self._intercept(
        request: request,
        options: options,
        name: "importStatefile",
        action: {
          (r: ImportStatefileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.Statefile
          in
          return try await self.inner.importStatefile(request: r, options: o)
        })
    }

    public func deleteStatefile(
      request: DeleteStatefileRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteStatefile",
        action: { (r: DeleteStatefileRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteStatefile(request: r, options: o)
        })
    }

    public func lockDeployment(
      request: LockDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "lockDeployment",
        action: {
          (r: LockDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.lockDeployment(request: r, options: o)
        })
    }

    public func unlockDeployment(
      request: UnlockDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "unlockDeployment",
        action: {
          (r: UnlockDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.unlockDeployment(request: r, options: o)
        })
    }

    public func exportLockInfo(
      request: ExportLockInfoRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.LockInfo {
      try await self._intercept(
        request: request,
        options: options,
        name: "exportLockInfo",
        action: {
          (r: ExportLockInfoRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.LockInfo
          in
          return try await self.inner.exportLockInfo(request: r, options: o)
        })
    }

    public func createPreview(
      request: CreatePreviewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createPreview",
        action: {
          (r: CreatePreviewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPreview(request: r, options: o)
        })
    }

    public func getPreview(
      request: GetPreviewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Preview {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPreview",
        action: {
          (r: GetPreviewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.Preview
          in
          return try await self.inner.getPreview(request: r, options: o)
        })
    }

    public func listPreviews(
      request: ListPreviewsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListPreviewsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPreviews",
        action: {
          (r: ListPreviewsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.ListPreviewsResponse
          in
          return try await self.inner.listPreviews(request: r, options: o)
        })
    }

    public func deletePreview(
      request: DeletePreviewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deletePreview",
        action: {
          (r: DeletePreviewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePreview(request: r, options: o)
        })
    }

    public func exportPreviewResult(
      request: ExportPreviewResultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ExportPreviewResultResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "exportPreviewResult",
        action: {
          (r: ExportPreviewResultRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.ExportPreviewResultResponse
          in
          return try await self.inner.exportPreviewResult(request: r, options: o)
        })
    }

    public func listTerraformVersions(
      request: ListTerraformVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListTerraformVersionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTerraformVersions",
        action: {
          (r: ListTerraformVersionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.ListTerraformVersionsResponse
          in
          return try await self.inner.listTerraformVersions(request: r, options: o)
        })
    }

    public func getTerraformVersion(
      request: GetTerraformVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.TerraformVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTerraformVersion",
        action: {
          (r: GetTerraformVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.TerraformVersion
          in
          return try await self.inner.getTerraformVersion(request: r, options: o)
        })
    }

    public func listResourceChanges(
      request: ListResourceChangesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListResourceChangesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listResourceChanges",
        action: {
          (r: ListResourceChangesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.ListResourceChangesResponse
          in
          return try await self.inner.listResourceChanges(request: r, options: o)
        })
    }

    public func getResourceChange(
      request: GetResourceChangeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ResourceChange {
      try await self._intercept(
        request: request,
        options: options,
        name: "getResourceChange",
        action: {
          (r: GetResourceChangeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.ResourceChange
          in
          return try await self.inner.getResourceChange(request: r, options: o)
        })
    }

    public func listResourceDrifts(
      request: ListResourceDriftsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListResourceDriftsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listResourceDrifts",
        action: {
          (r: ListResourceDriftsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.ListResourceDriftsResponse
          in
          return try await self.inner.listResourceDrifts(request: r, options: o)
        })
    }

    public func getResourceDrift(
      request: GetResourceDriftRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ResourceDrift {
      try await self._intercept(
        request: request,
        options: options,
        name: "getResourceDrift",
        action: {
          (r: GetResourceDriftRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.ResourceDrift
          in
          return try await self.inner.getResourceDrift(request: r, options: o)
        })
    }

    public func getAutoMigrationConfig(
      request: GetAutoMigrationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.AutoMigrationConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAutoMigrationConfig",
        action: {
          (r: GetAutoMigrationConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.AutoMigrationConfig
          in
          return try await self.inner.getAutoMigrationConfig(request: r, options: o)
        })
    }

    public func updateAutoMigrationConfig(
      request: UpdateAutoMigrationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateAutoMigrationConfig",
        action: {
          (r: UpdateAutoMigrationConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateAutoMigrationConfig(request: r, options: o)
        })
    }

    public func getDeploymentGroup(
      request: GetDeploymentGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.DeploymentGroup {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDeploymentGroup",
        action: {
          (r: GetDeploymentGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.DeploymentGroup
          in
          return try await self.inner.getDeploymentGroup(request: r, options: o)
        })
    }

    public func createDeploymentGroup(
      request: CreateDeploymentGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDeploymentGroup",
        action: {
          (r: CreateDeploymentGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDeploymentGroup(request: r, options: o)
        })
    }

    public func updateDeploymentGroup(
      request: UpdateDeploymentGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDeploymentGroup",
        action: {
          (r: UpdateDeploymentGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDeploymentGroup(request: r, options: o)
        })
    }

    public func deleteDeploymentGroup(
      request: DeleteDeploymentGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDeploymentGroup",
        action: {
          (r: DeleteDeploymentGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDeploymentGroup(request: r, options: o)
        })
    }

    public func listDeploymentGroups(
      request: ListDeploymentGroupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListDeploymentGroupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDeploymentGroups",
        action: {
          (r: ListDeploymentGroupsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.ListDeploymentGroupsResponse
          in
          return try await self.inner.listDeploymentGroups(request: r, options: o)
        })
    }

    public func provisionDeploymentGroup(
      request: ProvisionDeploymentGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "provisionDeploymentGroup",
        action: {
          (r: ProvisionDeploymentGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.provisionDeploymentGroup(request: r, options: o)
        })
    }

    public func deprovisionDeploymentGroup(
      request: DeprovisionDeploymentGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deprovisionDeploymentGroup",
        action: {
          (r: DeprovisionDeploymentGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deprovisionDeploymentGroup(request: r, options: o)
        })
    }

    public func getDeploymentGroupRevision(
      request: GetDeploymentGroupRevisionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.DeploymentGroupRevision {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDeploymentGroupRevision",
        action: {
          (r: GetDeploymentGroupRevisionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.DeploymentGroupRevision
          in
          return try await self.inner.getDeploymentGroupRevision(request: r, options: o)
        })
    }

    public func listDeploymentGroupRevisions(
      request: ListDeploymentGroupRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListDeploymentGroupRevisionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDeploymentGroupRevisions",
        action: {
          (r: ListDeploymentGroupRevisionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfigV1.ListDeploymentGroupRevisionsResponse
          in
          return try await self.inner.listDeploymentGroupRevisions(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
