// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol ConfigStub: Sendable {
    func listDeployments(
      request: ListDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListDeploymentsResponse

    func getDeployment(
      request: GetDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Deployment

    func createDeployment(
      request: CreateDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateDeployment(
      request: UpdateDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteDeployment(
      request: DeleteDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listRevisions(
      request: ListRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListRevisionsResponse

    func getRevision(
      request: GetRevisionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Revision

    func getResource(
      request: GetResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Resource

    func listResources(
      request: ListResourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListResourcesResponse

    func exportDeploymentStatefile(
      request: ExportDeploymentStatefileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Statefile

    func exportRevisionStatefile(
      request: ExportRevisionStatefileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Statefile

    func importStatefile(
      request: ImportStatefileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Statefile

    func deleteStatefile(
      request: DeleteStatefileRequest, options: GoogleGax.RequestOptions
    ) async throws

    func lockDeployment(
      request: LockDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func unlockDeployment(
      request: UnlockDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func exportLockInfo(
      request: ExportLockInfoRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.LockInfo

    func createPreview(
      request: CreatePreviewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getPreview(
      request: GetPreviewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.Preview

    func listPreviews(
      request: ListPreviewsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListPreviewsResponse

    func deletePreview(
      request: DeletePreviewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func exportPreviewResult(
      request: ExportPreviewResultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ExportPreviewResultResponse

    func listTerraformVersions(
      request: ListTerraformVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListTerraformVersionsResponse

    func getTerraformVersion(
      request: GetTerraformVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.TerraformVersion

    func listResourceChanges(
      request: ListResourceChangesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListResourceChangesResponse

    func getResourceChange(
      request: GetResourceChangeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ResourceChange

    func listResourceDrifts(
      request: ListResourceDriftsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListResourceDriftsResponse

    func getResourceDrift(
      request: GetResourceDriftRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ResourceDrift

    func getAutoMigrationConfig(
      request: GetAutoMigrationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.AutoMigrationConfig

    func updateAutoMigrationConfig(
      request: UpdateAutoMigrationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getDeploymentGroup(
      request: GetDeploymentGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.DeploymentGroup

    func createDeploymentGroup(
      request: CreateDeploymentGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateDeploymentGroup(
      request: UpdateDeploymentGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteDeploymentGroup(
      request: DeleteDeploymentGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listDeploymentGroups(
      request: ListDeploymentGroupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListDeploymentGroupsResponse

    func provisionDeploymentGroup(
      request: ProvisionDeploymentGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deprovisionDeploymentGroup(
      request: DeprovisionDeploymentGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getDeploymentGroupRevision(
      request: GetDeploymentGroupRevisionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.DeploymentGroupRevision

    func listDeploymentGroupRevisions(
      request: ListDeploymentGroupRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigV1.ListDeploymentGroupRevisionsResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
