// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for Delete DeploymentGroup
public struct DeleteDeploymentGroupRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of DeploymentGroup in the format
  /// projects/{project_id}/locations/{location_id}/deploymentGroups/{deploymentGroup}
  public var name: Swift.String = Swift.String()

  /// Optional. An optional request ID to identify requests. Specify a unique
  /// request ID so that if you must retry your request, the server will know to
  /// ignore the request if it has already been completed. The server will
  /// guarantee that for at least 60 minutes after the first request.
  ///
  /// For example, consider a situation where you make an initial request and the
  /// request times out. If you make the request again with the same request ID,
  /// the server can check if original operation with the same request ID was
  /// received, and if so, will ignore the second request. This prevents clients
  /// from accidentally creating duplicate commitments.
  ///
  /// The request ID must be a valid UUID with the exception that zero UUID is
  /// not supported (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Optional. If set to true, any revisions for this deployment group will also
  /// be deleted. (Otherwise, the request will only work if the deployment group
  /// has no revisions.)
  public var force: Swift.Bool = Swift.Bool()

  /// Optional. Policy on how to handle referenced deployments when deleting the
  /// DeploymentGroup.
  /// If unspecified, the default behavior is to fail the deletion if any
  /// deployments currently referenced in the `deployment_units` of the
  /// DeploymentGroup or in the latest revision are not deleted.
  public var deploymentReferencePolicy: DeleteDeploymentGroupRequest.DeploymentReferencePolicy =
    DeleteDeploymentGroupRequest.DeploymentReferencePolicy()

  /// Initialize a new instance of `DeleteDeploymentGroupRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeleteDeploymentGroupRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Policy on how to handle referenced deployments when deleting the
  /// DeploymentGroup.
  public enum DeploymentReferencePolicy: Codable, Equatable, Sendable {
    /// The default behavior. If unspecified, the system will act as if
    /// `FAIL_IF_ANY_REFERENCES_EXIST` is specified.
    case unspecified
    /// Fail the deletion if any deployments currently referenced in the
    /// `deployment_units` of the DeploymentGroup or in the latest revision
    /// are not deleted.
    case failIfAnyReferencesExist
    /// Fail the deletion only if any deployments currently referenced in the
    /// `deployment_units` of the DeploymentGroup are not deleted.
    /// The deletion will proceed even if the deployments in the latest revision
    /// of the DeploymentGroup are not deleted.
    case failIfMetadataReferencesExist
    /// Ignore any deployments currently referenced in the
    /// `deployment_units` of the DeploymentGroup or in the latest revision.
    case ignoreDeploymentReferences
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .failIfAnyReferencesExist: return 1
      case .failIfMetadataReferencesExist: return 2
      case .ignoreDeploymentReferences: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DEPLOYMENT_REFERENCE_POLICY_UNSPECIFIED"
      case .failIfAnyReferencesExist: return "FAIL_IF_ANY_REFERENCES_EXIST"
      case .failIfMetadataReferencesExist: return "FAIL_IF_METADATA_REFERENCES_EXIST"
      case .ignoreDeploymentReferences: return "IGNORE_DEPLOYMENT_REFERENCES"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DeploymentReferencePolicy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DEPLOYMENT_REFERENCE_POLICY_UNSPECIFIED": self = .unspecified
      case "FAIL_IF_ANY_REFERENCES_EXIST": self = .failIfAnyReferencesExist
      case "FAIL_IF_METADATA_REFERENCES_EXIST": self = .failIfMetadataReferencesExist
      case "IGNORE_DEPLOYMENT_REFERENCES": self = .ignoreDeploymentReferences
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DeploymentReferencePolicy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .failIfAnyReferencesExist
      case 2: self = .failIfMetadataReferencesExist
      case 3: self = .ignoreDeploymentReferences
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .failIfAnyReferencesExist: return try container.encode(1)
      case .failIfMetadataReferencesExist: return try container.encode(2)
      case .ignoreDeploymentReferences: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.DeleteDeploymentGroupRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
