// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Ephemeral metadata content describing the state of a deployment operation.
public struct DeploymentOperationMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The current step the deployment operation is running.
  public var step: DeploymentOperationMetadata.DeploymentStep =
    DeploymentOperationMetadata.DeploymentStep()

  /// Outputs and artifacts from applying a deployment.
  public var applyResults: ApplyResults? = nil

  /// Output only. Cloud Build instance UUID associated with this operation.
  public var build: Swift.String = Swift.String()

  /// Output only. Location of Deployment operations logs in
  /// `gs://{bucket}/{object}` format.
  public var logs: Swift.String = Swift.String()

  /// Initialize a new instance of `DeploymentOperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeploymentOperationMetadata().with { $0.step = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The possible steps a deployment may be running.
  public enum DeploymentStep: Codable, Equatable, Sendable {
    /// Unspecified deployment step
    case unspecified
    /// Infra Manager is creating a Google Cloud Storage bucket to store
    /// artifacts and metadata about the deployment and revision
    case preparingStorageBucket
    /// Downloading the blueprint onto the Google Cloud Storage bucket
    case downloadingBlueprint
    /// Initializing Terraform using `terraform init`
    case runningTfInit
    /// Running `terraform plan`
    case runningTfPlan
    /// Actuating resources using Terraform using `terraform apply`
    case runningTfApply
    /// Destroying resources using Terraform using `terraform destroy`
    case runningTfDestroy
    /// Validating the uploaded TF state file when unlocking a deployment
    case runningTfValidate
    /// Unlocking a deployment
    case unlockingDeployment
    /// Operation was successful
    case succeeded
    /// Operation failed
    case failed
    /// Validating the provided repository.
    case validatingRepository
    /// Running quota validation
    case runningQuotaValidation
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .preparingStorageBucket: return 1
      case .downloadingBlueprint: return 2
      case .runningTfInit: return 3
      case .runningTfPlan: return 4
      case .runningTfApply: return 5
      case .runningTfDestroy: return 6
      case .runningTfValidate: return 7
      case .unlockingDeployment: return 8
      case .succeeded: return 9
      case .failed: return 10
      case .validatingRepository: return 11
      case .runningQuotaValidation: return 12
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DEPLOYMENT_STEP_UNSPECIFIED"
      case .preparingStorageBucket: return "PREPARING_STORAGE_BUCKET"
      case .downloadingBlueprint: return "DOWNLOADING_BLUEPRINT"
      case .runningTfInit: return "RUNNING_TF_INIT"
      case .runningTfPlan: return "RUNNING_TF_PLAN"
      case .runningTfApply: return "RUNNING_TF_APPLY"
      case .runningTfDestroy: return "RUNNING_TF_DESTROY"
      case .runningTfValidate: return "RUNNING_TF_VALIDATE"
      case .unlockingDeployment: return "UNLOCKING_DEPLOYMENT"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .validatingRepository: return "VALIDATING_REPOSITORY"
      case .runningQuotaValidation: return "RUNNING_QUOTA_VALIDATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DeploymentStep/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DEPLOYMENT_STEP_UNSPECIFIED": self = .unspecified
      case "PREPARING_STORAGE_BUCKET": self = .preparingStorageBucket
      case "DOWNLOADING_BLUEPRINT": self = .downloadingBlueprint
      case "RUNNING_TF_INIT": self = .runningTfInit
      case "RUNNING_TF_PLAN": self = .runningTfPlan
      case "RUNNING_TF_APPLY": self = .runningTfApply
      case "RUNNING_TF_DESTROY": self = .runningTfDestroy
      case "RUNNING_TF_VALIDATE": self = .runningTfValidate
      case "UNLOCKING_DEPLOYMENT": self = .unlockingDeployment
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "VALIDATING_REPOSITORY": self = .validatingRepository
      case "RUNNING_QUOTA_VALIDATION": self = .runningQuotaValidation
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DeploymentStep/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .preparingStorageBucket
      case 2: self = .downloadingBlueprint
      case 3: self = .runningTfInit
      case 4: self = .runningTfPlan
      case 5: self = .runningTfApply
      case 6: self = .runningTfDestroy
      case 7: self = .runningTfValidate
      case 8: self = .unlockingDeployment
      case 9: self = .succeeded
      case 10: self = .failed
      case 11: self = .validatingRepository
      case 12: self = .runningQuotaValidation
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .preparingStorageBucket: return try container.encode(1)
      case .downloadingBlueprint: return try container.encode(2)
      case .runningTfInit: return try container.encode(3)
      case .runningTfPlan: return try container.encode(4)
      case .runningTfApply: return try container.encode(5)
      case .runningTfDestroy: return try container.encode(6)
      case .runningTfValidate: return try container.encode(7)
      case .unlockingDeployment: return try container.encode(8)
      case .succeeded: return try container.encode(9)
      case .failed: return try container.encode(10)
      case .validatingRepository: return try container.encode(11)
      case .runningQuotaValidation: return try container.encode(12)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.DeploymentOperationMetadata"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
