// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Deployment is a group of resources and configs managed and provisioned by
/// Infra Manager.
public struct Deployment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Resource name of the deployment.
  /// Format: `projects/{project}/locations/{location}/deployments/{deployment}`
  public var name: Swift.String = Swift.String()

  /// Output only. Time when the deployment was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time when the deployment was last modified.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. User-defined metadata for the deployment.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Current state of the deployment.
  public var state: Deployment.State = Deployment.State()

  /// Output only. Revision name that was most recently applied.
  /// Format: `projects/{project}/locations/{location}/deployments/{deployment}/
  /// revisions/{revision}`
  public var latestRevision: Swift.String = Swift.String()

  /// Output only. Additional information regarding the current state.
  public var stateDetail: Swift.String = Swift.String()

  /// Output only. Error code describing errors that may have occurred.
  public var errorCode: Deployment.ErrorCode = Deployment.ErrorCode()

  /// Output only. Location of artifacts from a DeleteDeployment operation.
  public var deleteResults: ApplyResults? = nil

  /// Output only. Cloud Build instance UUID associated with deleting this
  /// deployment.
  public var deleteBuild: Swift.String = Swift.String()

  /// Output only. Location of Cloud Build logs in Google Cloud Storage,
  /// populated when deleting this deployment. Format: `gs://{bucket}/{object}`.
  public var deleteLogs: Swift.String = Swift.String()

  /// Output only. Errors encountered when deleting this deployment.
  /// Errors are truncated to 10 entries, see `delete_results` and `error_logs`
  /// for full details.
  public var tfErrors: [TerraformError] = []

  /// Output only. Location of Terraform error logs in Google Cloud Storage.
  /// Format: `gs://{bucket}/{object}`.
  public var errorLogs: Swift.String = Swift.String()

  /// Optional. User-defined location of Cloud Build logs and artifacts in Google
  /// Cloud Storage. Format: `gs://{bucket}/{folder}`
  ///
  /// A default bucket will be bootstrapped if the field is not set or empty.
  /// Default bucket format: `gs://<project number>-<region>-blueprint-config`
  /// Constraints:
  /// - The bucket needs to be in the same project as the deployment
  /// - The path cannot be within the path of `gcs_source`
  /// - The field cannot be updated, including changing its presence
  public var artifactsGcsBucket: Swift.String? = nil

  /// Required. User-specified Service Account (SA) credentials to be used when
  /// actuating resources.
  /// Format: `projects/{projectID}/serviceAccounts/{serviceAccount}`
  public var serviceAccount: Swift.String? = nil

  /// By default, Infra Manager will return a failure when
  /// Terraform encounters a 409 code (resource conflict error) during actuation.
  /// If this flag is set to true, Infra Manager will instead
  /// attempt to automatically import the resource into the Terraform state (for
  /// supported resource types) and continue actuation.
  ///
  /// Not all resource types are supported, refer to documentation.
  public var importExistingResources: Swift.Bool? = nil

  /// Optional. The user-specified Cloud Build worker pool resource in which the
  /// Cloud Build job will execute. Format:
  /// `projects/{project}/locations/{location}/workerPools/{workerPoolId}`.
  /// If this field is unspecified, the default Cloud Build worker pool will be
  /// used.
  public var workerPool: Swift.String? = nil

  /// Output only. Current lock state of the deployment.
  public var lockState: Deployment.LockState = Deployment.LockState()

  /// Optional. The user-specified Terraform version constraint.
  /// Example: "=1.3.10".
  public var tfVersionConstraint: Swift.String? = nil

  /// Output only. The current Terraform version set on the deployment.
  /// It is in the format of "Major.Minor.Patch", for example, "1.3.10".
  public var tfVersion: Swift.String = Swift.String()

  /// Optional. Input to control quota checks for resources in terraform
  /// configuration files. There are limited resources on which quota validation
  /// applies.
  public var quotaValidation: QuotaValidation = QuotaValidation()

  /// Optional. Arbitrary key-value metadata storage e.g. to help client tools
  /// identify deployments during automation. See
  /// https://google.aip.dev/148#annotations for details on format and size
  /// limitations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. This field specifies the provider configurations.
  public var providerConfig: ProviderConfig? = nil

  /// Blueprint to deploy.
  public var blueprint: OneOf_Blueprint? = nil

  /// Initialize a new instance of `Deployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Deployment().with { $0.terraformBlueprint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case terraformBlueprint = "terraformBlueprint"
    case name = "name"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case labels = "labels"
    case state = "state"
    case latestRevision = "latestRevision"
    case stateDetail = "stateDetail"
    case errorCode = "errorCode"
    case deleteResults = "deleteResults"
    case deleteBuild = "deleteBuild"
    case deleteLogs = "deleteLogs"
    case tfErrors = "tfErrors"
    case errorLogs = "errorLogs"
    case artifactsGcsBucket = "artifactsGcsBucket"
    case serviceAccount = "serviceAccount"
    case importExistingResources = "importExistingResources"
    case workerPool = "workerPool"
    case lockState = "lockState"
    case tfVersionConstraint = "tfVersionConstraint"
    case tfVersion = "tfVersion"
    case quotaValidation = "quotaValidation"
    case annotations = "annotations"
    case providerConfig = "providerConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.state = try container.decode(Deployment.State.self, forKey: .state)
    self.latestRevision = try container.decode(Swift.String.self, forKey: .latestRevision)
    self.stateDetail = try container.decode(Swift.String.self, forKey: .stateDetail)
    self.errorCode = try container.decode(Deployment.ErrorCode.self, forKey: .errorCode)
    self.deleteResults = try container.decodeIfPresent(ApplyResults.self, forKey: .deleteResults)
    self.deleteBuild = try container.decode(Swift.String.self, forKey: .deleteBuild)
    self.deleteLogs = try container.decode(Swift.String.self, forKey: .deleteLogs)
    self.tfErrors = try container.decode([TerraformError].self, forKey: .tfErrors)
    self.errorLogs = try container.decode(Swift.String.self, forKey: .errorLogs)
    self.artifactsGcsBucket = try container.decodeIfPresent(
      Swift.String.self, forKey: .artifactsGcsBucket)
    self.serviceAccount = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount)
    self.importExistingResources = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .importExistingResources)
    self.workerPool = try container.decodeIfPresent(Swift.String.self, forKey: .workerPool)
    self.lockState = try container.decode(Deployment.LockState.self, forKey: .lockState)
    self.tfVersionConstraint = try container.decodeIfPresent(
      Swift.String.self, forKey: .tfVersionConstraint)
    self.tfVersion = try container.decode(Swift.String.self, forKey: .tfVersion)
    self.quotaValidation = try container.decode(QuotaValidation.self, forKey: .quotaValidation)
    self.annotations = try container.decode([Swift.String: Swift.String].self, forKey: .annotations)
    self.providerConfig = try container.decodeIfPresent(
      ProviderConfig.self, forKey: .providerConfig)

    var blueprint: OneOf_Blueprint? = nil
    let blueprintCheckAndSet = {
      if blueprint != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'blueprint'"))
      }
      blueprint = $0
    }
    if let terraformBlueprint = try container.decodeIfPresent(
      TerraformBlueprint?.self, forKey: .terraformBlueprint)
    {
      try blueprintCheckAndSet(.terraformBlueprint(terraformBlueprint))
    }
    self.blueprint = blueprint
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.latestRevision, forKey: .latestRevision)
    try container.encode(self.stateDetail, forKey: .stateDetail)
    try container.encode(self.errorCode, forKey: .errorCode)
    try container.encode(self.deleteResults, forKey: .deleteResults)
    try container.encode(self.deleteBuild, forKey: .deleteBuild)
    try container.encode(self.deleteLogs, forKey: .deleteLogs)
    try container.encode(self.tfErrors, forKey: .tfErrors)
    try container.encode(self.errorLogs, forKey: .errorLogs)
    try container.encode(self.artifactsGcsBucket, forKey: .artifactsGcsBucket)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.importExistingResources, forKey: .importExistingResources)
    try container.encode(self.workerPool, forKey: .workerPool)
    try container.encode(self.lockState, forKey: .lockState)
    try container.encode(self.tfVersionConstraint, forKey: .tfVersionConstraint)
    try container.encode(self.tfVersion, forKey: .tfVersion)
    try container.encode(self.quotaValidation, forKey: .quotaValidation)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.providerConfig, forKey: .providerConfig)

    if let choice = self.blueprint {
      switch choice {
      case .terraformBlueprint(let value):
        try container.encode(value, forKey: .terraformBlueprint)
      }
    }
  }

  /// Possible states of a deployment.
  public enum State: Codable, Equatable, Sendable {
    /// The default value. This value is used if the state is omitted.
    case unspecified
    /// The deployment is being created.
    case creating
    /// The deployment is healthy.
    case active
    /// The deployment is being updated.
    case updating
    /// The deployment is being deleted.
    case deleting
    /// The deployment has encountered an unexpected error.
    case failed
    /// The deployment is no longer being actively reconciled.
    /// This may be the result of recovering the project after deletion.
    case suspended
    /// The deployment has been deleted.
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .updating: return 3
      case .deleting: return 4
      case .failed: return 5
      case .suspended: return 6
      case .deleted: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .failed: return "FAILED"
      case .suspended: return "SUSPENDED"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "FAILED": self = .failed
      case "SUSPENDED": self = .suspended
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .updating
      case 4: self = .deleting
      case 5: self = .failed
      case 6: self = .suspended
      case 7: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .active: return try container.encode(2)
      case .updating: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .failed: return try container.encode(5)
      case .suspended: return try container.encode(6)
      case .deleted: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible errors that can occur with deployments.
  public enum ErrorCode: Codable, Equatable, Sendable {
    /// No error code was specified.
    case unspecified
    /// The revision failed. See Revision for more details.
    case revisionFailed
    /// Cloud Build failed due to a permission issue.
    case cloudBuildPermissionDenied
    /// Cloud Build job associated with a deployment deletion could not be
    /// started.
    case deleteBuildApiFailed
    /// Cloud Build job associated with a deployment deletion was started but
    /// failed.
    case deleteBuildRunFailed
    /// Cloud Storage bucket creation failed due to a permission issue.
    case bucketCreationPermissionDenied
    /// Cloud Storage bucket creation failed due to an issue unrelated to
    /// permissions.
    case bucketCreationFailed
    /// Failed to import values from an external source.
    case externalValueSourceImportFailed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .revisionFailed: return 1
      case .cloudBuildPermissionDenied: return 3
      case .deleteBuildApiFailed: return 5
      case .deleteBuildRunFailed: return 6
      case .bucketCreationPermissionDenied: return 7
      case .bucketCreationFailed: return 8
      case .externalValueSourceImportFailed: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ERROR_CODE_UNSPECIFIED"
      case .revisionFailed: return "REVISION_FAILED"
      case .cloudBuildPermissionDenied: return "CLOUD_BUILD_PERMISSION_DENIED"
      case .deleteBuildApiFailed: return "DELETE_BUILD_API_FAILED"
      case .deleteBuildRunFailed: return "DELETE_BUILD_RUN_FAILED"
      case .bucketCreationPermissionDenied: return "BUCKET_CREATION_PERMISSION_DENIED"
      case .bucketCreationFailed: return "BUCKET_CREATION_FAILED"
      case .externalValueSourceImportFailed: return "EXTERNAL_VALUE_SOURCE_IMPORT_FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ERROR_CODE_UNSPECIFIED": self = .unspecified
      case "REVISION_FAILED": self = .revisionFailed
      case "CLOUD_BUILD_PERMISSION_DENIED": self = .cloudBuildPermissionDenied
      case "DELETE_BUILD_API_FAILED": self = .deleteBuildApiFailed
      case "DELETE_BUILD_RUN_FAILED": self = .deleteBuildRunFailed
      case "BUCKET_CREATION_PERMISSION_DENIED": self = .bucketCreationPermissionDenied
      case "BUCKET_CREATION_FAILED": self = .bucketCreationFailed
      case "EXTERNAL_VALUE_SOURCE_IMPORT_FAILED": self = .externalValueSourceImportFailed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .revisionFailed
      case 3: self = .cloudBuildPermissionDenied
      case 5: self = .deleteBuildApiFailed
      case 6: self = .deleteBuildRunFailed
      case 7: self = .bucketCreationPermissionDenied
      case 8: self = .bucketCreationFailed
      case 10: self = .externalValueSourceImportFailed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .revisionFailed: return try container.encode(1)
      case .cloudBuildPermissionDenied: return try container.encode(3)
      case .deleteBuildApiFailed: return try container.encode(5)
      case .deleteBuildRunFailed: return try container.encode(6)
      case .bucketCreationPermissionDenied: return try container.encode(7)
      case .bucketCreationFailed: return try container.encode(8)
      case .externalValueSourceImportFailed: return try container.encode(10)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible lock states of a deployment.
  public enum LockState: Codable, Equatable, Sendable {
    /// The default value. This value is used if the lock state is omitted.
    case unspecified
    /// The deployment is locked.
    case locked
    /// The deployment is unlocked.
    case unlocked
    /// The deployment is being locked.
    case locking
    /// The deployment is being unlocked.
    case unlocking
    /// The deployment has failed to lock.
    case lockFailed
    /// The deployment has failed to unlock.
    case unlockFailed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .locked: return 1
      case .unlocked: return 2
      case .locking: return 3
      case .unlocking: return 4
      case .lockFailed: return 5
      case .unlockFailed: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "LOCK_STATE_UNSPECIFIED"
      case .locked: return "LOCKED"
      case .unlocked: return "UNLOCKED"
      case .locking: return "LOCKING"
      case .unlocking: return "UNLOCKING"
      case .lockFailed: return "LOCK_FAILED"
      case .unlockFailed: return "UNLOCK_FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "LOCK_STATE_UNSPECIFIED": self = .unspecified
      case "LOCKED": self = .locked
      case "UNLOCKED": self = .unlocked
      case "LOCKING": self = .locking
      case "UNLOCKING": self = .unlocking
      case "LOCK_FAILED": self = .lockFailed
      case "UNLOCK_FAILED": self = .unlockFailed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .locked
      case 2: self = .unlocked
      case 3: self = .locking
      case 4: self = .unlocking
      case 5: self = .lockFailed
      case 6: self = .unlockFailed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .locked: return try container.encode(1)
      case .unlocked: return try container.encode(2)
      case .locking: return try container.encode(3)
      case .unlocking: return try container.encode(4)
      case .lockFailed: return try container.encode(5)
      case .unlockFailed: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Blueprint to deploy.
  public enum OneOf_Blueprint: Codable, Equatable, Sendable {
    /// A blueprint described using Terraform's HashiCorp Configuration Language
    /// as a root module.
    indirect case terraformBlueprint(TerraformBlueprint?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.Deployment"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
