// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A DeploymentGroupRevision represents a snapshot of a
/// [DeploymentGroup][google.cloud.config.v1.DeploymentGroup] at a given point in
/// time, created when a DeploymentGroup is provisioned or deprovisioned.
///
/// [google.cloud.config.v1.DeploymentGroup]: <doc:DeploymentGroup>
public struct DeploymentGroupRevision: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The name of the deployment group revision.
  /// Format:
  /// 'projects/{project_id}/locations/{location}/deploymentGroups/{deployment_group}/revisions/{revision}'.
  public var name: Swift.String = Swift.String()

  /// Output only. The snapshot of the deployment group at this revision.
  public var snapshot: DeploymentGroup? = nil

  /// Output only. Time when the deployment group revision was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The alternative IDs of the deployment group revision.
  public var alternativeIds: [Swift.String] = []

  /// Initialize a new instance of `DeploymentGroupRevision`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeploymentGroupRevision().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.DeploymentGroupRevision"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
