// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A DeploymentUnit is a container for a deployment and its dependencies.
/// An existing deployment can be provided directly in the unit, or the unit
/// can act as a placeholder to define the DAG, with the deployment specs
/// supplied in a `provisionDeploymentRequest`.
public struct DeploymentUnit: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The id of the deployment unit. Must be unique within the deployment group.
  public var id: Swift.String = Swift.String()

  /// Optional. The name of the deployment to be provisioned.
  /// Format:
  /// 'projects/{project_id}/locations/{location}/deployments/{deployment}'.
  public var deployment: Swift.String? = nil

  /// Required. The IDs of the deployment units within the deployment group that
  /// this unit depends on.
  public var dependencies: [Swift.String] = []

  /// Initialize a new instance of `DeploymentUnit`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeploymentUnit().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.DeploymentUnit"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
