// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The summary of the deployment operation.
public struct DeploymentOperationSummary: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The current step the deployment operation is running.
  public var deploymentStep: DeploymentOperationMetadata.DeploymentStep =
    DeploymentOperationMetadata.DeploymentStep()

  /// Output only. Cloud Build instance UUID associated with this operation.
  public var build: Swift.String = Swift.String()

  /// Output only. Location of Deployment operations logs in
  /// `gs://{bucket}/{object}` format.
  public var logs: Swift.String = Swift.String()

  /// Output only. Location of Deployment operations content in
  /// `gs://{bucket}/{object}` format.
  public var content: Swift.String = Swift.String()

  /// Output only. Location of Deployment operations artifacts in
  /// `gs://{bucket}/{object}` format.
  public var artifacts: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DeploymentOperationSummary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeploymentOperationSummary().with { $0.deploymentStep = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let deploymentStep = CodingKeys(stringValue: "deploymentStep")
    static let build = CodingKeys(stringValue: "build")
    static let logs = CodingKeys(stringValue: "logs")
    static let content = CodingKeys(stringValue: "content")
    static let artifacts = CodingKeys(stringValue: "artifacts")

    static let _knownKeys: Set<Swift.String> = [
      "deploymentStep",
      "build",
      "logs",
      "content",
      "artifacts",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      DeploymentOperationMetadata.DeploymentStep.self, forKey: .deploymentStep)
    {
      self.deploymentStep = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .build) {
      self.build = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .logs) {
      self.logs = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .content) {
      self.content = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .artifacts) {
      self.artifacts = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.deploymentStep, forKey: .deploymentStep)
    try container.encode(self.build, forKey: .build)
    try container.encode(self.logs, forKey: .logs)
    try container.encode(self.content, forKey: .content)
    try container.encode(self.artifacts, forKey: .artifacts)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.DeploymentOperationSummary"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
