// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// The progress of a deployment unit provisioning or deprovisioning.
public struct DeploymentUnitProgress: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The unit id of the deployment unit to be provisioned.
  public var unitId: Swift.String = Swift.String()

  /// Output only. The name of the deployment to be provisioned.
  /// Format:
  /// 'projects/{project}/locations/{location}/deployments/{deployment}'.
  public var deployment: Swift.String = Swift.String()

  /// Output only. The current step of the deployment unit provisioning.
  public var state: DeploymentUnitProgress.State = DeploymentUnitProgress.State()

  /// Output only. Additional information regarding the current state.
  public var stateDescription: Swift.String = Swift.String()

  /// Output only. The summary of the deployment operation.
  public var deploymentOperationSummary: DeploymentOperationSummary? = nil

  /// Output only. Holds the error status of the deployment unit provisioning.
  public var error: GoogleRpc.Status? = nil

  /// Output only. The intent of the deployment unit.
  public var intent: DeploymentUnitProgress.Intent = DeploymentUnitProgress.Intent()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `DeploymentUnitProgress`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeploymentUnitProgress().with { $0.unitId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let unitId = CodingKeys(stringValue: "unitId")
    static let deployment = CodingKeys(stringValue: "deployment")
    static let state = CodingKeys(stringValue: "state")
    static let stateDescription = CodingKeys(stringValue: "stateDescription")
    static let deploymentOperationSummary = CodingKeys(stringValue: "deploymentOperationSummary")
    static let error = CodingKeys(stringValue: "error")
    static let intent = CodingKeys(stringValue: "intent")

    static let _knownKeys: Set<Swift.String> = [
      "unitId",
      "deployment",
      "state",
      "stateDescription",
      "deploymentOperationSummary",
      "error",
      "intent",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .unitId) {
      self.unitId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .deployment) {
      self.deployment = value
    }
    if let value = try container.decodeIfPresent(DeploymentUnitProgress.State.self, forKey: .state)
    {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stateDescription) {
      self.stateDescription = value
    }
    self.deploymentOperationSummary = try container.decodeIfPresent(
      DeploymentOperationSummary.self, forKey: .deploymentOperationSummary)
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    if let value = try container.decodeIfPresent(
      DeploymentUnitProgress.Intent.self, forKey: .intent)
    {
      self.intent = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.unitId, forKey: .unitId)
    try container.encode(self.deployment, forKey: .deployment)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateDescription, forKey: .stateDescription)
    try container.encodeIfPresent(
      self.deploymentOperationSummary, forKey: .deploymentOperationSummary)
    try container.encodeIfPresent(self.error, forKey: .error)
    try container.encode(self.intent, forKey: .intent)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The possible steps a deployment unit provisioning may be running.
  public enum State: Codable, Equatable, Sendable {
    /// The default value. This value is unused.
    case unspecified
    /// The deployment unit is queued for deployment creation or update.
    case queued
    /// The underlying deployment of the unit is being created or updated.
    case applyingDeployment
    /// The underlying deployment operation of the unit has succeeded.
    case succeeded
    /// The underlying deployment operation of the unit has failed.
    case failed
    /// The deployment unit was aborted, likely due to failures in other
    /// dependent deployment units.
    case aborted
    /// The deployment unit was skipped because there were no changes to apply.
    case skipped
    /// The deployment is being deleted.
    case deletingDeployment
    /// The deployment is being previewed.
    case previewingDeployment
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .queued: return 1
      case .applyingDeployment: return 2
      case .succeeded: return 4
      case .failed: return 5
      case .aborted: return 6
      case .skipped: return 7
      case .deletingDeployment: return 8
      case .previewingDeployment: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .queued: return "QUEUED"
      case .applyingDeployment: return "APPLYING_DEPLOYMENT"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .aborted: return "ABORTED"
      case .skipped: return "SKIPPED"
      case .deletingDeployment: return "DELETING_DEPLOYMENT"
      case .previewingDeployment: return "PREVIEWING_DEPLOYMENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "QUEUED": self = .queued
      case "APPLYING_DEPLOYMENT": self = .applyingDeployment
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "ABORTED": self = .aborted
      case "SKIPPED": self = .skipped
      case "DELETING_DEPLOYMENT": self = .deletingDeployment
      case "PREVIEWING_DEPLOYMENT": self = .previewingDeployment
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .queued
      case 2: self = .applyingDeployment
      case 4: self = .succeeded
      case 5: self = .failed
      case 6: self = .aborted
      case 7: self = .skipped
      case 8: self = .deletingDeployment
      case 9: self = .previewingDeployment
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .queued: return try container.encode("QUEUED")
      case .applyingDeployment: return try container.encode("APPLYING_DEPLOYMENT")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .failed: return try container.encode("FAILED")
      case .aborted: return try container.encode("ABORTED")
      case .skipped: return try container.encode("SKIPPED")
      case .deletingDeployment: return try container.encode("DELETING_DEPLOYMENT")
      case .previewingDeployment: return try container.encode("PREVIEWING_DEPLOYMENT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The possible intents of a deployment unit.
  public enum Intent: Codable, Equatable, Sendable {
    /// Unspecified intent.
    case unspecified
    /// Create deployment in the unit from the deployment spec.
    case createDeployment
    /// Update deployment in the unit.
    case updateDeployment
    /// Delete deployment in the unit.
    case deleteDeployment
    /// Recreate deployment in the unit.
    case recreateDeployment
    /// Delete deployment in latest successful revision while no longer
    /// referenced in any deployment unit in the current deployment group.
    case cleanUp
    /// Expected to be unchanged.
    case unchanged
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .createDeployment: return 1
      case .updateDeployment: return 2
      case .deleteDeployment: return 3
      case .recreateDeployment: return 4
      case .cleanUp: return 5
      case .unchanged: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INTENT_UNSPECIFIED"
      case .createDeployment: return "CREATE_DEPLOYMENT"
      case .updateDeployment: return "UPDATE_DEPLOYMENT"
      case .deleteDeployment: return "DELETE_DEPLOYMENT"
      case .recreateDeployment: return "RECREATE_DEPLOYMENT"
      case .cleanUp: return "CLEAN_UP"
      case .unchanged: return "UNCHANGED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Intent/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INTENT_UNSPECIFIED": self = .unspecified
      case "CREATE_DEPLOYMENT": self = .createDeployment
      case "UPDATE_DEPLOYMENT": self = .updateDeployment
      case "DELETE_DEPLOYMENT": self = .deleteDeployment
      case "RECREATE_DEPLOYMENT": self = .recreateDeployment
      case "CLEAN_UP": self = .cleanUp
      case "UNCHANGED": self = .unchanged
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Intent/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .createDeployment
      case 2: self = .updateDeployment
      case 3: self = .deleteDeployment
      case 4: self = .recreateDeployment
      case 5: self = .cleanUp
      case 6: self = .unchanged
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("INTENT_UNSPECIFIED")
      case .createDeployment: return try container.encode("CREATE_DEPLOYMENT")
      case .updateDeployment: return try container.encode("UPDATE_DEPLOYMENT")
      case .deleteDeployment: return try container.encode("DELETE_DEPLOYMENT")
      case .recreateDeployment: return try container.encode("RECREATE_DEPLOYMENT")
      case .cleanUp: return try container.encode("CLEAN_UP")
      case .unchanged: return try container.encode("UNCHANGED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.DeploymentUnitProgress"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
