// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// A DeploymentGroup is a collection of DeploymentUnits that in a DAG-like
/// structure.
public struct DeploymentGroup: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the deployment group.
  /// Format:
  /// 'projects/{project_id}/locations/{location}/deploymentGroups/{deployment_group}'.
  public var name: Swift.String = Swift.String()

  /// Output only. Time when the deployment group was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time when the deployment group was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. User-defined metadata for the deployment group.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Arbitrary key-value metadata storage e.g. to help client tools
  /// identify deployment group during automation. See
  /// https://google.aip.dev/148#annotations for details on format and size
  /// limitations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. Current state of the deployment group.
  public var state: DeploymentGroup.State = DeploymentGroup.State()

  /// Output only. Additional information regarding the current state.
  public var stateDescription: Swift.String = Swift.String()

  /// The deployment units of the deployment group in a DAG like structure.
  /// When a deployment group is being provisioned, the deployment units are
  /// deployed in a DAG order.
  /// The provided units must be in a DAG order, otherwise an error will be
  /// returned.
  public var deploymentUnits: [DeploymentUnit] = []

  /// Output only. The provisioning state of the deployment group.
  public var provisioningState: DeploymentGroup.ProvisioningState =
    DeploymentGroup.ProvisioningState()

  /// Output only. Additional information regarding the current provisioning
  /// state.
  public var provisioningStateDescription: Swift.String = Swift.String()

  /// Output only. The error status of the deployment group provisioning or
  /// deprovisioning.
  public var provisioningError: GoogleRpc.Status? = nil

  /// Initialize a new instance of `DeploymentGroup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeploymentGroup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible states of a deployment group.
  public enum State: Codable, Equatable, Sendable {
    /// The default value. This value is used if the state is omitted.
    case unspecified
    /// The deployment group is being created.
    case creating
    /// The deployment group is healthy.
    case active
    /// The deployment group is being updated.
    case updating
    /// The deployment group is being deleted.
    case deleting
    /// The deployment group has encountered an unexpected error.
    case failed
    /// The deployment group is no longer being actively reconciled.
    /// This may be the result of recovering the project after deletion.
    case suspended
    /// The deployment group has been deleted.
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .updating: return 3
      case .deleting: return 4
      case .failed: return 5
      case .suspended: return 6
      case .deleted: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .failed: return "FAILED"
      case .suspended: return "SUSPENDED"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "FAILED": self = .failed
      case "SUSPENDED": self = .suspended
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .updating
      case 4: self = .deleting
      case 5: self = .failed
      case 6: self = .suspended
      case 7: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .active: return try container.encode(2)
      case .updating: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .failed: return try container.encode(5)
      case .suspended: return try container.encode(6)
      case .deleted: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible provisioning states of a deployment group.
  public enum ProvisioningState: Codable, Equatable, Sendable {
    /// Unspecified provisioning state.
    case unspecified
    /// The deployment group is being provisioned.
    case provisioning
    /// The deployment group is provisioned.
    case provisioned
    /// The deployment group failed to be provisioned.
    case failedToProvision
    /// The deployment group is being deprovisioned.
    case deprovisioning
    /// The deployment group is deprovisioned.
    case deprovisioned
    /// The deployment group failed to be deprovisioned.
    case failedToDeprovision
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .provisioning: return 1
      case .provisioned: return 2
      case .failedToProvision: return 3
      case .deprovisioning: return 4
      case .deprovisioned: return 5
      case .failedToDeprovision: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PROVISIONING_STATE_UNSPECIFIED"
      case .provisioning: return "PROVISIONING"
      case .provisioned: return "PROVISIONED"
      case .failedToProvision: return "FAILED_TO_PROVISION"
      case .deprovisioning: return "DEPROVISIONING"
      case .deprovisioned: return "DEPROVISIONED"
      case .failedToDeprovision: return "FAILED_TO_DEPROVISION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ProvisioningState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PROVISIONING_STATE_UNSPECIFIED": self = .unspecified
      case "PROVISIONING": self = .provisioning
      case "PROVISIONED": self = .provisioned
      case "FAILED_TO_PROVISION": self = .failedToProvision
      case "DEPROVISIONING": self = .deprovisioning
      case "DEPROVISIONED": self = .deprovisioned
      case "FAILED_TO_DEPROVISION": self = .failedToDeprovision
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ProvisioningState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .provisioning
      case 2: self = .provisioned
      case 3: self = .failedToProvision
      case 4: self = .deprovisioning
      case 5: self = .deprovisioned
      case 6: self = .failedToDeprovision
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .provisioning: return try container.encode(1)
      case .provisioned: return try container.encode(2)
      case .failedToProvision: return try container.encode(3)
      case .deprovisioning: return try container.encode(4)
      case .deprovisioned: return try container.encode(5)
      case .failedToDeprovision: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.DeploymentGroup"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
