// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request message for the DeprovisionDeploymentGroup method.
public struct DeprovisionDeploymentGroupRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the deployment group to deprovision.
  /// Format:
  /// 'projects/{project_id}/locations/{location}/deploymentGroups/{deployment_group}'.
  public var name: Swift.String = Swift.String()

  /// Optional. If set to true, this option is propagated to the deletion of each
  /// deployment in the group. This corresponds to the 'force' field
  /// in DeleteDeploymentRequest.
  public var force: Swift.Bool = Swift.Bool()

  /// Optional. Policy on how resources within each deployment should be handled
  /// during deletion. This policy is applied globally to the deletion of all
  /// deployments in this group. This corresponds to the 'delete_policy' field
  /// in DeleteDeploymentRequest.
  public var deletePolicy: DeleteDeploymentRequest.DeletePolicy =
    DeleteDeploymentRequest.DeletePolicy()

  /// Initialize a new instance of `DeprovisionDeploymentGroupRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeprovisionDeploymentGroupRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.DeprovisionDeploymentGroupRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
