// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A set of files in a Git repository.
public struct GitSource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Repository URL.
  /// Example: 'https://github.com/kubernetes/examples.git'
  public var repo: Swift.String? = nil

  /// Subdirectory inside the repository.
  /// Example: 'staging/my-package'
  public var directory: Swift.String? = nil

  /// Git reference (e.g. branch or tag).
  public var ref: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `GitSource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitSource().with { $0.repo = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let repo = CodingKeys(stringValue: "repo")
    static let directory = CodingKeys(stringValue: "directory")
    static let ref = CodingKeys(stringValue: "ref")

    static let _knownKeys: Set<Swift.String> = [
      "repo",
      "directory",
      "ref",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.repo = try container.decodeIfPresent(Swift.String.self, forKey: .repo)
    self.directory = try container.decodeIfPresent(Swift.String.self, forKey: .directory)
    self.ref = try container.decodeIfPresent(Swift.String.self, forKey: .ref)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.repo, forKey: .repo)
    try container.encodeIfPresent(self.directory, forKey: .directory)
    try container.encodeIfPresent(self.ref, forKey: .ref)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.GitSource"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
