// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A request to list Revisions passed to a 'ListRevisions' call.
public struct ListRevisionsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent in whose context the Revisions are listed. The parent
  /// value is in the format:
  /// 'projects/{project_id}/locations/{location}/deployments/{deployment}'.
  public var parent: Swift.String = Swift.String()

  /// When requesting a page of resources, `page_size` specifies number of
  /// resources to return. If unspecified, at most 500 will be returned. The
  /// maximum value is 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Token returned by previous call to 'ListRevisions' which specifies the
  /// position in the list from where to continue listing the resources.
  public var pageToken: Swift.String = Swift.String()

  /// Lists the Revisions that match the filter expression. A filter
  /// expression filters the resources listed in the response. The expression
  /// must be of the form '{field} {operator} {value}' where operators: '<', '>',
  /// '<=', '>=', '!=', '=', ':' are supported (colon ':' represents a HAS
  /// operator which is roughly synonymous with equality). {field} can refer to a
  /// proto or JSON field, or a synthetic field. Field names can be camelCase or
  /// snake_case.
  ///
  /// Examples:
  /// - Filter by name:
  ///   name = "projects/foo/locations/us-central1/deployments/dep/revisions/bar
  ///
  /// - Filter by labels:
  ///   - Resources that have a key called 'foo'
  ///     labels.foo:*
  ///   - Resources that have a key called 'foo' whose value is 'bar'
  ///     labels.foo = bar
  ///
  /// - Filter by state:
  ///   - Revisions in CREATING state.
  ///     state=CREATING
  public var filter: Swift.String = Swift.String()

  /// Field to use to sort the list.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListRevisionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListRevisionsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.ListRevisionsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
