// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message for the ListResourceDrifts method.
public struct ListResourceDriftsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent in whose context the ResourceDrifts are listed. The
  /// parent value is in the format:
  /// 'projects/{project_id}/locations/{location}/previews/{preview}'.
  public var parent: Swift.String = Swift.String()

  /// Optional. When requesting a page of resource drifts, 'page_size' specifies
  /// number of resource drifts to return. If unspecified, at most 500 will be
  /// returned. The maximum value is 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. Token returned by previous call to 'ListResourceDrifts' which
  /// specifies the position in the list from where to continue listing the
  /// resource drifts.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Lists the resource drifts that match the filter expression. A
  /// filter expression filters the resource drifts listed in the response. The
  /// expression must be of the form '{field} {operator} {value}' where
  /// operators: '<', '>',
  /// '<=',
  /// '>=',
  /// '!=', '=', ':' are supported (colon ':' represents a HAS operator which is
  /// roughly synonymous with equality). {field} can refer to a proto or JSON
  /// field, or a synthetic field. Field names can be camelCase or snake_case.
  ///
  /// Examples:
  /// - Filter by name:
  ///   name =
  ///   "projects/foo/locations/us-central1/previews/dep/resourceDrifts/baz
  public var filter: Swift.String = Swift.String()

  /// Optional. Field to use to sort the list.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListResourceDriftsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListResourceDriftsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.ListResourceDriftsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
