// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message for the ListDeploymentGroupRevisions method.
public struct ListDeploymentGroupRevisionsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent, which owns this collection of deployment group
  /// revisions. Format:
  /// 'projects/{project_id}/locations/{location}/deploymentGroups/{deployment_group}'.
  public var parent: Swift.String = Swift.String()

  /// Optional. When requesting a page of resources, 'page_size' specifies number
  /// of resources to return. If unspecified, a sensible default will be used by
  /// the server. The maximum value is 1000; values above 1000 will be coerced to
  /// 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. Token returned by previous call to 'ListDeploymentGroupRevisions'
  /// which specifies the position in the list from where to continue listing the
  /// deployment group revisions. All other parameters provided to
  /// `ListDeploymentGroupRevisions` must match the call that provided the page
  /// token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListDeploymentGroupRevisionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListDeploymentGroupRevisionsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.ListDeploymentGroupRevisionsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
