// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Details about the lock which locked the deployment.
public struct LockInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Unique ID for the lock to be overridden with generation ID in the backend.
  public var lockId: Swift.Int64 = Swift.Int64()

  /// Terraform operation, provided by the caller.
  public var operation: Swift.String = Swift.String()

  /// Extra information to store with the lock, provided by the caller.
  public var info: Swift.String = Swift.String()

  /// user@hostname when available
  public var who: Swift.String = Swift.String()

  /// Terraform version
  public var version: Swift.String = Swift.String()

  /// Time that the lock was taken.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `LockInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LockInfo().with { $0.lockId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let lockId = CodingKeys(stringValue: "lockId")
    static let operation = CodingKeys(stringValue: "operation")
    static let info = CodingKeys(stringValue: "info")
    static let who = CodingKeys(stringValue: "who")
    static let version = CodingKeys(stringValue: "version")
    static let createTime = CodingKeys(stringValue: "createTime")

    static let _knownKeys: Set<Swift.String> = [
      "lockId",
      "operation",
      "info",
      "who",
      "version",
      "createTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .lockId) {
      self.lockId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .operation) {
      self.operation = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .info) {
      self.info = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .who) {
      self.who = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.lockId, forKey: .lockId)
    try container.encode(self.operation, forKey: .operation)
    try container.encode(self.info, forKey: .info)
    try container.encode(self.who, forKey: .who)
    try container.encode(self.version, forKey: .version)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.LockInfo"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
