// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Details about the lock which locked the deployment.
public struct LockInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Unique ID for the lock to be overridden with generation ID in the backend.
  public var lockId: Swift.Int64 = Swift.Int64()

  /// Terraform operation, provided by the caller.
  public var operation: Swift.String = Swift.String()

  /// Extra information to store with the lock, provided by the caller.
  public var info: Swift.String = Swift.String()

  /// user@hostname when available
  public var who: Swift.String = Swift.String()

  /// Terraform version
  public var version: Swift.String = Swift.String()

  /// Time that the lock was taken.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `LockInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LockInfo().with { $0.lockId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.LockInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
