// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents the metadata of the long-running operation.
public struct OperationMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Time when the operation was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time when the operation finished running.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Server-defined resource path for the target of the operation.
  public var target: Swift.String = Swift.String()

  /// Output only. Name of the verb executed by the operation.
  public var verb: Swift.String = Swift.String()

  /// Output only. Human-readable status of the operation, if any.
  public var statusMessage: Swift.String = Swift.String()

  /// Output only. Identifies whether the user has requested cancellation of the
  /// operation. Operations that have successfully been cancelled have
  /// [google.longrunning.Operation.error][google.longrunning.Operation.error]
  /// value with a [google.rpc.Status.code][google.rpc.Status.code] of `1`,
  /// corresponding to `Code.CANCELLED`.
  ///
  /// [google.longrunning.Operation.error]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/error
  /// [google.rpc.Status.code]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Status/code
  public var requestedCancellation: Swift.Bool = Swift.Bool()

  /// Output only. API version used to start the operation.
  public var apiVersion: Swift.String = Swift.String()

  /// Ephemeral metadata about the state of an operation for a particular
  /// resource.
  public var resourceMetadata: OneOf_ResourceMetadata? = nil

  /// Initialize a new instance of `OperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OperationMetadata().with { $0.deploymentMetadata = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case deploymentMetadata = "deploymentMetadata"
    case previewMetadata = "previewMetadata"
    case provisionDeploymentGroupMetadata = "provisionDeploymentGroupMetadata"
    case createTime = "createTime"
    case endTime = "endTime"
    case target = "target"
    case verb = "verb"
    case statusMessage = "statusMessage"
    case requestedCancellation = "requestedCancellation"
    case apiVersion = "apiVersion"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.endTime = try container.decodeIfPresent(GoogleCloudWkt.Timestamp.self, forKey: .endTime)
    self.target = try container.decode(Swift.String.self, forKey: .target)
    self.verb = try container.decode(Swift.String.self, forKey: .verb)
    self.statusMessage = try container.decode(Swift.String.self, forKey: .statusMessage)
    self.requestedCancellation = try container.decode(
      Swift.Bool.self, forKey: .requestedCancellation)
    self.apiVersion = try container.decode(Swift.String.self, forKey: .apiVersion)

    var resourceMetadata: OneOf_ResourceMetadata? = nil
    let resourceMetadataCheckAndSet = {
      if resourceMetadata != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'resourceMetadata'"))
      }
      resourceMetadata = $0
    }
    if let deploymentMetadata = try container.decodeIfPresent(
      DeploymentOperationMetadata?.self, forKey: .deploymentMetadata)
    {
      try resourceMetadataCheckAndSet(.deploymentMetadata(deploymentMetadata))
    }
    if let previewMetadata = try container.decodeIfPresent(
      PreviewOperationMetadata?.self, forKey: .previewMetadata)
    {
      try resourceMetadataCheckAndSet(.previewMetadata(previewMetadata))
    }
    if let provisionDeploymentGroupMetadata = try container.decodeIfPresent(
      ProvisionDeploymentGroupOperationMetadata?.self, forKey: .provisionDeploymentGroupMetadata)
    {
      try resourceMetadataCheckAndSet(
        .provisionDeploymentGroupMetadata(provisionDeploymentGroupMetadata))
    }
    self.resourceMetadata = resourceMetadata
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.endTime, forKey: .endTime)
    try container.encode(self.target, forKey: .target)
    try container.encode(self.verb, forKey: .verb)
    try container.encode(self.statusMessage, forKey: .statusMessage)
    try container.encode(self.requestedCancellation, forKey: .requestedCancellation)
    try container.encode(self.apiVersion, forKey: .apiVersion)

    if let choice = self.resourceMetadata {
      switch choice {
      case .deploymentMetadata(let value):
        try container.encode(value, forKey: .deploymentMetadata)
      case .previewMetadata(let value):
        try container.encode(value, forKey: .previewMetadata)
      case .provisionDeploymentGroupMetadata(let value):
        try container.encode(value, forKey: .provisionDeploymentGroupMetadata)
      }
    }
  }

  /// Ephemeral metadata about the state of an operation for a particular
  /// resource.
  public enum OneOf_ResourceMetadata: Codable, Equatable, Sendable {
    /// Output only. Metadata about the deployment operation state.
    indirect case deploymentMetadata(DeploymentOperationMetadata?)
    /// Output only. Metadata about the preview operation state.
    indirect case previewMetadata(PreviewOperationMetadata?)
    /// Output only. Metadata about ProvisionDeploymentGroup operation state.
    indirect case provisionDeploymentGroupMetadata(ProvisionDeploymentGroupOperationMetadata?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.OperationMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
