// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Represents the metadata of the long-running operation.
public struct OperationMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Time when the operation was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. Time when the operation finished running.
  public var endTime: GoogleWKT.Timestamp? = nil

  /// Output only. Server-defined resource path for the target of the operation.
  public var target: Swift.String = Swift.String()

  /// Output only. Name of the verb executed by the operation.
  public var verb: Swift.String = Swift.String()

  /// Output only. Human-readable status of the operation, if any.
  public var statusMessage: Swift.String = Swift.String()

  /// Output only. Identifies whether the user has requested cancellation of the
  /// operation. Operations that have successfully been cancelled have
  /// [google.longrunning.Operation.error][google.longrunning.Operation.error]
  /// value with a [google.rpc.Status.code][google.rpc.Status.code] of `1`,
  /// corresponding to `Code.CANCELLED`.
  ///
  /// [google.longrunning.Operation.error]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/OneOf_Result/error(_:)
  /// [google.rpc.Status.code]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Status/code
  public var requestedCancellation: Swift.Bool = Swift.Bool()

  /// Output only. API version used to start the operation.
  public var apiVersion: Swift.String = Swift.String()

  /// Ephemeral metadata about the state of an operation for a particular
  /// resource.
  public var resourceMetadata: OneOf_ResourceMetadata? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OperationMetadata().with { $0.deploymentMetadata = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let deploymentMetadata = CodingKeys(stringValue: "deploymentMetadata")
    static let previewMetadata = CodingKeys(stringValue: "previewMetadata")
    static let provisionDeploymentGroupMetadata = CodingKeys(
      stringValue: "provisionDeploymentGroupMetadata")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let target = CodingKeys(stringValue: "target")
    static let verb = CodingKeys(stringValue: "verb")
    static let statusMessage = CodingKeys(stringValue: "statusMessage")
    static let requestedCancellation = CodingKeys(stringValue: "requestedCancellation")
    static let apiVersion = CodingKeys(stringValue: "apiVersion")

    static let _knownKeys: Set<Swift.String> = [
      "deploymentMetadata",
      "previewMetadata",
      "provisionDeploymentGroupMetadata",
      "createTime",
      "endTime",
      "target",
      "verb",
      "statusMessage",
      "requestedCancellation",
      "apiVersion",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .target) {
      self.target = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .verb) {
      self.verb = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .statusMessage) {
      self.statusMessage = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .requestedCancellation) {
      self.requestedCancellation = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .apiVersion) {
      self.apiVersion = value
    }

    var resourceMetadata: OneOf_ResourceMetadata? = nil
    let resourceMetadataCheckAndSet = {
      if resourceMetadata != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'resourceMetadata'"))
      }
      resourceMetadata = $0
    }
    if let deploymentMetadata = try container.decodeIfPresent(
      DeploymentOperationMetadata?.self, forKey: .deploymentMetadata)
    {
      try resourceMetadataCheckAndSet(.deploymentMetadata(deploymentMetadata))
    }
    if let previewMetadata = try container.decodeIfPresent(
      PreviewOperationMetadata?.self, forKey: .previewMetadata)
    {
      try resourceMetadataCheckAndSet(.previewMetadata(previewMetadata))
    }
    if let provisionDeploymentGroupMetadata = try container.decodeIfPresent(
      ProvisionDeploymentGroupOperationMetadata?.self, forKey: .provisionDeploymentGroupMetadata)
    {
      try resourceMetadataCheckAndSet(
        .provisionDeploymentGroupMetadata(provisionDeploymentGroupMetadata))
    }
    self.resourceMetadata = resourceMetadata
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.target, forKey: .target)
    try container.encode(self.verb, forKey: .verb)
    try container.encode(self.statusMessage, forKey: .statusMessage)
    try container.encode(self.requestedCancellation, forKey: .requestedCancellation)
    try container.encode(self.apiVersion, forKey: .apiVersion)

    if let choice = self.resourceMetadata {
      switch choice {
      case .deploymentMetadata(let value):
        try container.encode(value, forKey: .deploymentMetadata)
      case .previewMetadata(let value):
        try container.encode(value, forKey: .previewMetadata)
      case .provisionDeploymentGroupMetadata(let value):
        try container.encode(value, forKey: .provisionDeploymentGroupMetadata)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Ephemeral metadata about the state of an operation for a particular
  /// resource.
  public enum OneOf_ResourceMetadata: Codable, Equatable, Sendable {
    /// Output only. Metadata about the deployment operation state.
    indirect case deploymentMetadata(DeploymentOperationMetadata?)
    /// Output only. Metadata about the preview operation state.
    indirect case previewMetadata(PreviewOperationMetadata?)
    /// Output only. Metadata about ProvisionDeploymentGroup operation state.
    indirect case provisionDeploymentGroupMetadata(ProvisionDeploymentGroupOperationMetadata?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.OperationMetadata"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
