// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleRpc

/// A preview represents a set of actions Infra Manager would perform
/// to move the resources towards the desired state as specified in the
/// configuration.
public struct Preview: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Resource name of the preview. Resource name can be user
  /// provided or server generated ID if unspecified. Format:
  /// `projects/{project}/locations/{location}/previews/{preview}`
  public var name: Swift.String = Swift.String()

  /// Output only. Time the preview was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. User-defined labels for the preview.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Current state of the preview.
  public var state: Preview.State = Preview.State()

  /// Optional. Optional deployment reference. If specified, the preview will be
  /// performed using the provided deployment's current state and use any
  /// relevant fields from the deployment unless explicitly specified in the
  /// preview create request.
  public var deployment: Swift.String = Swift.String()

  /// Optional. Current mode of preview.
  public var previewMode: Preview.PreviewMode = Preview.PreviewMode()

  /// Required. User-specified Service Account (SA) credentials to be used when
  /// previewing resources.
  /// Format: `projects/{projectID}/serviceAccounts/{serviceAccount}`
  public var serviceAccount: Swift.String = Swift.String()

  /// Optional. User-defined location of Cloud Build logs, artifacts, and
  /// in Google Cloud Storage.
  /// Format: `gs://{bucket}/{folder}`
  /// A default bucket will be bootstrapped if the field is not set or empty
  /// Default Bucket Format: `gs://<project number>-<region>-blueprint-config`
  /// Constraints:
  /// - The bucket needs to be in the same project as the deployment
  /// - The path cannot be within the path of `gcs_source`
  /// If omitted and deployment resource ref provided has artifacts_gcs_bucket
  /// defined, that artifact bucket is used.
  public var artifactsGcsBucket: Swift.String? = nil

  /// Optional. The user-specified Worker Pool resource in which the Cloud Build
  /// job will execute. Format
  /// projects/{project}/locations/{location}/workerPools/{workerPoolId} If this
  /// field is unspecified, the default Cloud Build worker pool will be used. If
  /// omitted and deployment resource ref provided has worker_pool defined, that
  /// worker pool is used.
  public var workerPool: Swift.String? = nil

  /// Output only. Code describing any errors that may have occurred.
  public var errorCode: Preview.ErrorCode = Preview.ErrorCode()

  /// Output only. Additional information regarding the current state.
  public var errorStatus: GoogleRpc.Status? = nil

  /// Output only. Cloud Build instance UUID associated with this preview.
  public var build: Swift.String = Swift.String()

  /// Output only. Summary of errors encountered during Terraform preview.
  /// It has a size limit of 10, i.e. only top 10 errors will be summarized here.
  public var tfErrors: [TerraformError] = []

  /// Output only. Link to tf-error.ndjson file, which contains the full list of
  /// the errors encountered during a Terraform preview.
  /// Format: `gs://{bucket}/{object}`.
  public var errorLogs: Swift.String = Swift.String()

  /// Output only. Artifacts from preview.
  public var previewArtifacts: PreviewArtifacts? = nil

  /// Output only. Location of preview logs in `gs://{bucket}/{object}` format.
  public var logs: Swift.String = Swift.String()

  /// Output only. The current Terraform version set on the preview.
  /// It is in the format of "Major.Minor.Patch", for example, "1.3.10".
  public var tfVersion: Swift.String = Swift.String()

  /// Optional. The user-specified Terraform version constraint.
  /// Example: "=1.3.10".
  public var tfVersionConstraint: Swift.String? = nil

  /// Optional. Arbitrary key-value metadata storage e.g. to help client tools
  /// identify preview during automation. See
  /// https://google.aip.dev/148#annotations for details on format and size
  /// limitations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. This field specifies the provider configurations.
  public var providerConfig: ProviderConfig? = nil

  /// Blueprint to preview.
  public var blueprint: OneOf_Blueprint? = nil

  /// Initialize a new instance of `Preview`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Preview().with { $0.terraformBlueprint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case terraformBlueprint = "terraformBlueprint"
    case name = "name"
    case createTime = "createTime"
    case labels = "labels"
    case state = "state"
    case deployment = "deployment"
    case previewMode = "previewMode"
    case serviceAccount = "serviceAccount"
    case artifactsGcsBucket = "artifactsGcsBucket"
    case workerPool = "workerPool"
    case errorCode = "errorCode"
    case errorStatus = "errorStatus"
    case build = "build"
    case tfErrors = "tfErrors"
    case errorLogs = "errorLogs"
    case previewArtifacts = "previewArtifacts"
    case logs = "logs"
    case tfVersion = "tfVersion"
    case tfVersionConstraint = "tfVersionConstraint"
    case annotations = "annotations"
    case providerConfig = "providerConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.state = try container.decode(Preview.State.self, forKey: .state)
    self.deployment = try container.decode(Swift.String.self, forKey: .deployment)
    self.previewMode = try container.decode(Preview.PreviewMode.self, forKey: .previewMode)
    self.serviceAccount = try container.decode(Swift.String.self, forKey: .serviceAccount)
    self.artifactsGcsBucket = try container.decodeIfPresent(
      Swift.String.self, forKey: .artifactsGcsBucket)
    self.workerPool = try container.decodeIfPresent(Swift.String.self, forKey: .workerPool)
    self.errorCode = try container.decode(Preview.ErrorCode.self, forKey: .errorCode)
    self.errorStatus = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .errorStatus)
    self.build = try container.decode(Swift.String.self, forKey: .build)
    self.tfErrors = try container.decode([TerraformError].self, forKey: .tfErrors)
    self.errorLogs = try container.decode(Swift.String.self, forKey: .errorLogs)
    self.previewArtifacts = try container.decodeIfPresent(
      PreviewArtifacts.self, forKey: .previewArtifacts)
    self.logs = try container.decode(Swift.String.self, forKey: .logs)
    self.tfVersion = try container.decode(Swift.String.self, forKey: .tfVersion)
    self.tfVersionConstraint = try container.decodeIfPresent(
      Swift.String.self, forKey: .tfVersionConstraint)
    self.annotations = try container.decode([Swift.String: Swift.String].self, forKey: .annotations)
    self.providerConfig = try container.decodeIfPresent(
      ProviderConfig.self, forKey: .providerConfig)

    var blueprint: OneOf_Blueprint? = nil
    let blueprintCheckAndSet = {
      if blueprint != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'blueprint'"))
      }
      blueprint = $0
    }
    if let terraformBlueprint = try container.decodeIfPresent(
      TerraformBlueprint?.self, forKey: .terraformBlueprint)
    {
      try blueprintCheckAndSet(.terraformBlueprint(terraformBlueprint))
    }
    self.blueprint = blueprint
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.deployment, forKey: .deployment)
    try container.encode(self.previewMode, forKey: .previewMode)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.artifactsGcsBucket, forKey: .artifactsGcsBucket)
    try container.encode(self.workerPool, forKey: .workerPool)
    try container.encode(self.errorCode, forKey: .errorCode)
    try container.encode(self.errorStatus, forKey: .errorStatus)
    try container.encode(self.build, forKey: .build)
    try container.encode(self.tfErrors, forKey: .tfErrors)
    try container.encode(self.errorLogs, forKey: .errorLogs)
    try container.encode(self.previewArtifacts, forKey: .previewArtifacts)
    try container.encode(self.logs, forKey: .logs)
    try container.encode(self.tfVersion, forKey: .tfVersion)
    try container.encode(self.tfVersionConstraint, forKey: .tfVersionConstraint)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.providerConfig, forKey: .providerConfig)

    if let choice = self.blueprint {
      switch choice {
      case .terraformBlueprint(let value):
        try container.encode(value, forKey: .terraformBlueprint)
      }
    }
  }

  /// Possible states of a preview.
  public enum State: Codable, Equatable, Sendable {
    /// The default value. This value is used if the state is unknown.
    case unspecified
    /// The preview is being created.
    case creating
    /// The preview has succeeded.
    case succeeded
    /// The preview is being applied.
    case applying
    /// The preview is stale. A preview can become stale if a revision has been
    /// applied after this preview was created.
    case stale
    /// The preview is being deleted.
    case deleting
    /// The preview has encountered an unexpected error.
    case failed
    /// The preview has been deleted.
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .succeeded: return 2
      case .applying: return 3
      case .stale: return 4
      case .deleting: return 5
      case .failed: return 6
      case .deleted: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .succeeded: return "SUCCEEDED"
      case .applying: return "APPLYING"
      case .stale: return "STALE"
      case .deleting: return "DELETING"
      case .failed: return "FAILED"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "SUCCEEDED": self = .succeeded
      case "APPLYING": self = .applying
      case "STALE": self = .stale
      case "DELETING": self = .deleting
      case "FAILED": self = .failed
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .succeeded
      case 3: self = .applying
      case 4: self = .stale
      case 5: self = .deleting
      case 6: self = .failed
      case 7: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .succeeded: return try container.encode(2)
      case .applying: return try container.encode(3)
      case .stale: return try container.encode(4)
      case .deleting: return try container.encode(5)
      case .failed: return try container.encode(6)
      case .deleted: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Preview mode provides options for customizing preview operations.
  public enum PreviewMode: Codable, Equatable, Sendable {
    /// Unspecified policy, default mode will be used.
    case unspecified
    /// DEFAULT mode generates an execution plan for reconciling current resource
    /// state into expected resource state.
    case `default`
    /// DELETE mode generates as execution plan for destroying current resources.
    case delete
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`default`: return 1
      case .delete: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PREVIEW_MODE_UNSPECIFIED"
      case .`default`: return "DEFAULT"
      case .delete: return "DELETE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PreviewMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PREVIEW_MODE_UNSPECIFIED": self = .unspecified
      case "DEFAULT": self = .`default`
      case "DELETE": self = .delete
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PreviewMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`default`
      case 2: self = .delete
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .`default`: return try container.encode(1)
      case .delete: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible errors that can occur with previews.
  public enum ErrorCode: Codable, Equatable, Sendable {
    /// No error code was specified.
    case unspecified
    /// Cloud Build failed due to a permissions issue.
    case cloudBuildPermissionDenied
    /// Cloud Storage bucket failed to create due to a permissions issue.
    case bucketCreationPermissionDenied
    /// Cloud Storage bucket failed for a non-permissions-related issue.
    case bucketCreationFailed
    /// Acquiring lock on provided deployment reference failed.
    case deploymentLockAcquireFailed
    /// Preview encountered an error when trying to access Cloud Build API.
    case previewBuildApiFailed
    /// Preview created a build but build failed and logs were generated.
    case previewBuildRunFailed
    /// Failed to import values from an external source.
    case externalValueSourceImportFailed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cloudBuildPermissionDenied: return 1
      case .bucketCreationPermissionDenied: return 2
      case .bucketCreationFailed: return 3
      case .deploymentLockAcquireFailed: return 4
      case .previewBuildApiFailed: return 5
      case .previewBuildRunFailed: return 6
      case .externalValueSourceImportFailed: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ERROR_CODE_UNSPECIFIED"
      case .cloudBuildPermissionDenied: return "CLOUD_BUILD_PERMISSION_DENIED"
      case .bucketCreationPermissionDenied: return "BUCKET_CREATION_PERMISSION_DENIED"
      case .bucketCreationFailed: return "BUCKET_CREATION_FAILED"
      case .deploymentLockAcquireFailed: return "DEPLOYMENT_LOCK_ACQUIRE_FAILED"
      case .previewBuildApiFailed: return "PREVIEW_BUILD_API_FAILED"
      case .previewBuildRunFailed: return "PREVIEW_BUILD_RUN_FAILED"
      case .externalValueSourceImportFailed: return "EXTERNAL_VALUE_SOURCE_IMPORT_FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ErrorCode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ERROR_CODE_UNSPECIFIED": self = .unspecified
      case "CLOUD_BUILD_PERMISSION_DENIED": self = .cloudBuildPermissionDenied
      case "BUCKET_CREATION_PERMISSION_DENIED": self = .bucketCreationPermissionDenied
      case "BUCKET_CREATION_FAILED": self = .bucketCreationFailed
      case "DEPLOYMENT_LOCK_ACQUIRE_FAILED": self = .deploymentLockAcquireFailed
      case "PREVIEW_BUILD_API_FAILED": self = .previewBuildApiFailed
      case "PREVIEW_BUILD_RUN_FAILED": self = .previewBuildRunFailed
      case "EXTERNAL_VALUE_SOURCE_IMPORT_FAILED": self = .externalValueSourceImportFailed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ErrorCode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cloudBuildPermissionDenied
      case 2: self = .bucketCreationPermissionDenied
      case 3: self = .bucketCreationFailed
      case 4: self = .deploymentLockAcquireFailed
      case 5: self = .previewBuildApiFailed
      case 6: self = .previewBuildRunFailed
      case 7: self = .externalValueSourceImportFailed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .cloudBuildPermissionDenied: return try container.encode(1)
      case .bucketCreationPermissionDenied: return try container.encode(2)
      case .bucketCreationFailed: return try container.encode(3)
      case .deploymentLockAcquireFailed: return try container.encode(4)
      case .previewBuildApiFailed: return try container.encode(5)
      case .previewBuildRunFailed: return try container.encode(6)
      case .externalValueSourceImportFailed: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Blueprint to preview.
  public enum OneOf_Blueprint: Codable, Equatable, Sendable {
    /// The terraform blueprint to preview.
    indirect case terraformBlueprint(TerraformBlueprint?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.Preview"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
