// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Ephemeral metadata content describing the state of a preview operation.
public struct PreviewOperationMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The current step the preview operation is running.
  public var step: PreviewOperationMetadata.PreviewStep = PreviewOperationMetadata.PreviewStep()

  /// Artifacts from preview.
  public var previewArtifacts: PreviewArtifacts? = nil

  /// Output only. Location of preview logs in `gs://{bucket}/{object}` format.
  public var logs: Swift.String = Swift.String()

  /// Output only. Cloud Build instance UUID associated with this preview.
  public var build: Swift.String = Swift.String()

  /// Initialize a new instance of `PreviewOperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PreviewOperationMetadata().with { $0.step = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The possible steps a preview may be running.
  public enum PreviewStep: Codable, Equatable, Sendable {
    /// Unspecified preview step.
    case unspecified
    /// Infra Manager is creating a Google Cloud Storage bucket to store
    /// artifacts and metadata about the preview.
    case preparingStorageBucket
    /// Downloading the blueprint onto the Google Cloud Storage bucket.
    case downloadingBlueprint
    /// Initializing Terraform using `terraform init`.
    case runningTfInit
    /// Running `terraform plan`.
    case runningTfPlan
    /// Fetching a deployment.
    case fetchingDeployment
    /// Locking a deployment.
    case lockingDeployment
    /// Unlocking a deployment.
    case unlockingDeployment
    /// Operation was successful.
    case succeeded
    /// Operation failed.
    case failed
    /// Validating the provided repository.
    case validatingRepository
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .preparingStorageBucket: return 1
      case .downloadingBlueprint: return 2
      case .runningTfInit: return 3
      case .runningTfPlan: return 4
      case .fetchingDeployment: return 5
      case .lockingDeployment: return 6
      case .unlockingDeployment: return 7
      case .succeeded: return 8
      case .failed: return 9
      case .validatingRepository: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PREVIEW_STEP_UNSPECIFIED"
      case .preparingStorageBucket: return "PREPARING_STORAGE_BUCKET"
      case .downloadingBlueprint: return "DOWNLOADING_BLUEPRINT"
      case .runningTfInit: return "RUNNING_TF_INIT"
      case .runningTfPlan: return "RUNNING_TF_PLAN"
      case .fetchingDeployment: return "FETCHING_DEPLOYMENT"
      case .lockingDeployment: return "LOCKING_DEPLOYMENT"
      case .unlockingDeployment: return "UNLOCKING_DEPLOYMENT"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .validatingRepository: return "VALIDATING_REPOSITORY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PreviewStep/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PREVIEW_STEP_UNSPECIFIED": self = .unspecified
      case "PREPARING_STORAGE_BUCKET": self = .preparingStorageBucket
      case "DOWNLOADING_BLUEPRINT": self = .downloadingBlueprint
      case "RUNNING_TF_INIT": self = .runningTfInit
      case "RUNNING_TF_PLAN": self = .runningTfPlan
      case "FETCHING_DEPLOYMENT": self = .fetchingDeployment
      case "LOCKING_DEPLOYMENT": self = .lockingDeployment
      case "UNLOCKING_DEPLOYMENT": self = .unlockingDeployment
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "VALIDATING_REPOSITORY": self = .validatingRepository
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PreviewStep/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .preparingStorageBucket
      case 2: self = .downloadingBlueprint
      case 3: self = .runningTfInit
      case 4: self = .runningTfPlan
      case 5: self = .fetchingDeployment
      case 6: self = .lockingDeployment
      case 7: self = .unlockingDeployment
      case 8: self = .succeeded
      case 9: self = .failed
      case 10: self = .validatingRepository
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .preparingStorageBucket: return try container.encode(1)
      case .downloadingBlueprint: return try container.encode(2)
      case .runningTfInit: return try container.encode(3)
      case .runningTfPlan: return try container.encode(4)
      case .fetchingDeployment: return try container.encode(5)
      case .lockingDeployment: return try container.encode(6)
      case .unlockingDeployment: return try container.encode(7)
      case .succeeded: return try container.encode(8)
      case .failed: return try container.encode(9)
      case .validatingRepository: return try container.encode(10)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.PreviewOperationMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
