// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A property change represents a change to a property in the state file.
public struct PropertyChange: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The path of the property change.
  public var path: Swift.String = Swift.String()

  /// Output only. The paths of sensitive fields in `before`. Paths are relative
  /// to `path`.
  public var beforeSensitivePaths: [Swift.String] = []

  /// Output only. Representations of the object value before the actions.
  public var before: GoogleWKT.Value? = nil

  /// Output only. The paths of sensitive fields in `after`. Paths are relative
  /// to `path`.
  public var afterSensitivePaths: [Swift.String] = []

  /// Output only. Representations of the object value after the actions.
  public var after: GoogleWKT.Value? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PropertyChange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PropertyChange().with { $0.path = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let path = CodingKeys(stringValue: "path")
    static let beforeSensitivePaths = CodingKeys(stringValue: "beforeSensitivePaths")
    static let before = CodingKeys(stringValue: "before")
    static let afterSensitivePaths = CodingKeys(stringValue: "afterSensitivePaths")
    static let after = CodingKeys(stringValue: "after")

    static let _knownKeys: Set<Swift.String> = [
      "path",
      "beforeSensitivePaths",
      "before",
      "afterSensitivePaths",
      "after",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .path) {
      self.path = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .beforeSensitivePaths)
    {
      self.beforeSensitivePaths = value
    }
    self.before = try container.decodeIfPresent(GoogleWKT.Value.self, forKey: .before)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .afterSensitivePaths)
    {
      self.afterSensitivePaths = value
    }
    self.after = try container.decodeIfPresent(GoogleWKT.Value.self, forKey: .after)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.path, forKey: .path)
    try container.encode(self.beforeSensitivePaths, forKey: .beforeSensitivePaths)
    try container.encodeIfPresent(self.before, forKey: .before)
    try container.encode(self.afterSensitivePaths, forKey: .afterSensitivePaths)
    try container.encodeIfPresent(self.after, forKey: .after)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.PropertyChange"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
