// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A property change represents a change to a property in the state file.
public struct PropertyChange: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The path of the property change.
  public var path: Swift.String = Swift.String()

  /// Output only. The paths of sensitive fields in `before`. Paths are relative
  /// to `path`.
  public var beforeSensitivePaths: [Swift.String] = []

  /// Output only. Representations of the object value before the actions.
  public var before: GoogleCloudWKT.Value? = nil

  /// Output only. The paths of sensitive fields in `after`. Paths are relative
  /// to `path`.
  public var afterSensitivePaths: [Swift.String] = []

  /// Output only. Representations of the object value after the actions.
  public var after: GoogleCloudWKT.Value? = nil

  /// Initialize a new instance of `PropertyChange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PropertyChange().with { $0.path = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.PropertyChange"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
