// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Operation metadata for `ProvisionDeploymentGroup` and
/// `DeprovisionDeploymentGroup` long-running operations.
public struct ProvisionDeploymentGroupOperationMetadata: Codable, Equatable, GoogleCloudWKT
    ._AnyPackable,
  Sendable
{
  /// Output only. The current step of the deployment group operation.
  public var step: ProvisionDeploymentGroupOperationMetadata.ProvisionDeploymentGroupStep =
    ProvisionDeploymentGroupOperationMetadata.ProvisionDeploymentGroupStep()

  /// Output only. Progress information for each deployment unit within the
  /// operation.
  public var deploymentUnitProgresses: [DeploymentUnitProgress] = []

  /// Initialize a new instance of `ProvisionDeploymentGroupOperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProvisionDeploymentGroupOperationMetadata().with { $0.step = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible steps during a deployment group provisioning or deprovisioning
  /// operation.
  public enum ProvisionDeploymentGroupStep: Codable, Equatable, Sendable {
    /// Unspecified step.
    case unspecified
    /// Validating the deployment group.
    case validatingDeploymentGroup
    /// Locking the deployments to the deployment group for atomic actuation.
    case associatingDeploymentsToDeploymentGroup
    /// Provisioning the deployment units.
    case provisioningDeploymentUnits
    /// Unlocking the deployments from the deployment group after actuation.
    case disassociatingDeploymentsFromDeploymentGroup
    /// The operation has succeeded.
    case succeeded
    /// The operation has failed.
    case failed
    /// Deprovisioning the deployment units.
    case deprovisioningDeploymentUnits
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .validatingDeploymentGroup: return 1
      case .associatingDeploymentsToDeploymentGroup: return 2
      case .provisioningDeploymentUnits: return 3
      case .disassociatingDeploymentsFromDeploymentGroup: return 4
      case .succeeded: return 5
      case .failed: return 6
      case .deprovisioningDeploymentUnits: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PROVISION_DEPLOYMENT_GROUP_STEP_UNSPECIFIED"
      case .validatingDeploymentGroup: return "VALIDATING_DEPLOYMENT_GROUP"
      case .associatingDeploymentsToDeploymentGroup:
        return "ASSOCIATING_DEPLOYMENTS_TO_DEPLOYMENT_GROUP"
      case .provisioningDeploymentUnits: return "PROVISIONING_DEPLOYMENT_UNITS"
      case .disassociatingDeploymentsFromDeploymentGroup:
        return "DISASSOCIATING_DEPLOYMENTS_FROM_DEPLOYMENT_GROUP"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .deprovisioningDeploymentUnits: return "DEPROVISIONING_DEPLOYMENT_UNITS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ProvisionDeploymentGroupStep/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PROVISION_DEPLOYMENT_GROUP_STEP_UNSPECIFIED": self = .unspecified
      case "VALIDATING_DEPLOYMENT_GROUP": self = .validatingDeploymentGroup
      case "ASSOCIATING_DEPLOYMENTS_TO_DEPLOYMENT_GROUP":
        self = .associatingDeploymentsToDeploymentGroup
      case "PROVISIONING_DEPLOYMENT_UNITS": self = .provisioningDeploymentUnits
      case "DISASSOCIATING_DEPLOYMENTS_FROM_DEPLOYMENT_GROUP":
        self = .disassociatingDeploymentsFromDeploymentGroup
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "DEPROVISIONING_DEPLOYMENT_UNITS": self = .deprovisioningDeploymentUnits
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ProvisionDeploymentGroupStep/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .validatingDeploymentGroup
      case 2: self = .associatingDeploymentsToDeploymentGroup
      case 3: self = .provisioningDeploymentUnits
      case 4: self = .disassociatingDeploymentsFromDeploymentGroup
      case 5: self = .succeeded
      case 6: self = .failed
      case 7: self = .deprovisioningDeploymentUnits
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .validatingDeploymentGroup: return try container.encode(1)
      case .associatingDeploymentsToDeploymentGroup: return try container.encode(2)
      case .provisioningDeploymentUnits: return try container.encode(3)
      case .disassociatingDeploymentsFromDeploymentGroup: return try container.encode(4)
      case .succeeded: return try container.encode(5)
      case .failed: return try container.encode(6)
      case .deprovisioningDeploymentUnits: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.ProvisionDeploymentGroupOperationMetadata"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
