// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Resource represents a Google Cloud Platform resource actuated by IM.
/// Resources are child resources of Revisions.
public struct Resource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Resource name.
  /// Format:
  /// `projects/{project}/locations/{location}/deployments/{deployment}/revisions/{revision}/resources/{resource}`
  public var name: Swift.String = Swift.String()

  /// Output only. Terraform-specific info if this resource was created using
  /// Terraform.
  public var terraformInfo: ResourceTerraformInfo? = nil

  /// Output only. Map of Cloud Asset Inventory (CAI) type to CAI info (e.g. CAI
  /// ID). CAI type format follows
  /// https://cloud.google.com/asset-inventory/docs/supported-asset-types
  public var caiAssets: [Swift.String: ResourceCAIInfo] = [:]

  /// Output only. Intent of the resource.
  public var intent: Resource.Intent = Resource.Intent()

  /// Output only. Current state of the resource.
  public var state: Resource.State = Resource.State()

  /// Initialize a new instance of `Resource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Resource().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible intent of the resource.
  public enum Intent: Codable, Equatable, Sendable {
    /// The default value. This value is used if the intent is omitted.
    case unspecified
    /// Infra Manager will create this Resource.
    case create
    /// Infra Manager will update this Resource.
    case update
    /// Infra Manager will delete this Resource.
    case delete
    /// Infra Manager will destroy and recreate this Resource.
    case recreate
    /// Infra Manager will leave this Resource untouched.
    case unchanged
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .create: return 1
      case .update: return 2
      case .delete: return 3
      case .recreate: return 4
      case .unchanged: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INTENT_UNSPECIFIED"
      case .create: return "CREATE"
      case .update: return "UPDATE"
      case .delete: return "DELETE"
      case .recreate: return "RECREATE"
      case .unchanged: return "UNCHANGED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INTENT_UNSPECIFIED": self = .unspecified
      case "CREATE": self = .create
      case "UPDATE": self = .update
      case "DELETE": self = .delete
      case "RECREATE": self = .recreate
      case "UNCHANGED": self = .unchanged
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .create
      case 2: self = .update
      case 3: self = .delete
      case 4: self = .recreate
      case 5: self = .unchanged
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .create: return try container.encode(1)
      case .update: return try container.encode(2)
      case .delete: return try container.encode(3)
      case .recreate: return try container.encode(4)
      case .unchanged: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible states of a resource.
  public enum State: Codable, Equatable, Sendable {
    /// The default value. This value is used if the state is omitted.
    case unspecified
    /// Resource has been planned for reconcile.
    case planned
    /// Resource is actively reconciling into the intended state.
    case inProgress
    /// Resource has reconciled to intended state.
    case reconciled
    /// Resource failed to reconcile.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .planned: return 1
      case .inProgress: return 2
      case .reconciled: return 3
      case .failed: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .planned: return "PLANNED"
      case .inProgress: return "IN_PROGRESS"
      case .reconciled: return "RECONCILED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PLANNED": self = .planned
      case "IN_PROGRESS": self = .inProgress
      case "RECONCILED": self = .reconciled
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .planned
      case 2: self = .inProgress
      case 3: self = .reconciled
      case 4: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .planned: return try container.encode(1)
      case .inProgress: return try container.encode(2)
      case .reconciled: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.Resource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
