// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Terraform info of a ResourceChange.
public struct ResourceChangeTerraformInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. TF resource address that uniquely identifies the resource.
  public var address: Swift.String = Swift.String()

  /// Output only. TF resource type.
  public var type: Swift.String = Swift.String()

  /// Output only. TF resource name.
  public var resourceName: Swift.String = Swift.String()

  /// Output only. TF resource provider.
  public var provider: Swift.String = Swift.String()

  /// Output only. TF resource actions.
  public var actions: [Swift.String] = []

  /// Initialize a new instance of `ResourceChangeTerraformInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceChangeTerraformInfo().with { $0.address = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.ResourceChangeTerraformInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
