// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A resource change represents a change to a resource in the state file.
public struct ResourceChange: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the resource change.
  /// Format:
  /// 'projects/{project_id}/locations/{location}/previews/{preview}/resourceChanges/{resource_change}'.
  public var name: Swift.String = Swift.String()

  /// Output only. Terraform info of the resource change.
  public var terraformInfo: ResourceChangeTerraformInfo? = nil

  /// Output only. The intent of the resource change.
  public var intent: ResourceChange.Intent = ResourceChange.Intent()

  /// Output only. The property changes of the resource change.
  public var propertyChanges: [PropertyChange] = []

  /// Initialize a new instance of `ResourceChange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceChange().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible intent of the resource change.
  public enum Intent: Codable, Equatable, Sendable {
    /// The default value.
    case unspecified
    /// The resource will be created.
    case create
    /// The resource will be updated.
    case update
    /// The resource will be deleted.
    case delete
    /// The resource will be recreated.
    case recreate
    /// The resource will be untouched.
    case unchanged
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .create: return 1
      case .update: return 2
      case .delete: return 3
      case .recreate: return 4
      case .unchanged: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INTENT_UNSPECIFIED"
      case .create: return "CREATE"
      case .update: return "UPDATE"
      case .delete: return "DELETE"
      case .recreate: return "RECREATE"
      case .unchanged: return "UNCHANGED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Intent/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INTENT_UNSPECIFIED": self = .unspecified
      case "CREATE": self = .create
      case "UPDATE": self = .update
      case "DELETE": self = .delete
      case "RECREATE": self = .recreate
      case "UNCHANGED": self = .unchanged
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Intent/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .create
      case 2: self = .update
      case 3: self = .delete
      case 4: self = .recreate
      case 5: self = .unchanged
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .create: return try container.encode(1)
      case .update: return try container.encode(2)
      case .delete: return try container.encode(3)
      case .recreate: return try container.encode(4)
      case .unchanged: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.ResourceChange"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
