// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A child resource of a Deployment generated by a 'CreateDeployment' or
/// 'UpdateDeployment' call. Each Revision contains metadata pertaining to a
/// snapshot of a particular Deployment.
public struct Revision: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Revision name. Format:
  /// `projects/{project}/locations/{location}/deployments/{deployment}/
  /// revisions/{revision}`
  public var name: Swift.String = Swift.String()

  /// Output only. Time when the revision was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time when the revision was last modified.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The action which created this revision
  public var action: Revision.Action = Revision.Action()

  /// Output only. Current state of the revision.
  public var state: Revision.State = Revision.State()

  /// Output only. Outputs and artifacts from applying a deployment.
  public var applyResults: ApplyResults? = nil

  /// Output only. Additional info regarding the current state.
  public var stateDetail: Swift.String = Swift.String()

  /// Output only. Code describing any errors that may have occurred.
  public var errorCode: Revision.ErrorCode = Revision.ErrorCode()

  /// Output only. Cloud Build instance UUID associated with this revision.
  public var build: Swift.String = Swift.String()

  /// Output only. Location of Revision operation logs in
  /// `gs://{bucket}/{object}` format.
  public var logs: Swift.String = Swift.String()

  /// Output only. Errors encountered when creating or updating this deployment.
  /// Errors are truncated to 10 entries, see `delete_results` and `error_logs`
  /// for full details.
  public var tfErrors: [TerraformError] = []

  /// Output only. Location of Terraform error logs in Google Cloud Storage.
  /// Format: `gs://{bucket}/{object}`.
  public var errorLogs: Swift.String = Swift.String()

  /// Output only. User-specified Service Account (SA) to be used as credential
  /// to manage resources. Format:
  /// `projects/{projectID}/serviceAccounts/{serviceAccount}`
  public var serviceAccount: Swift.String = Swift.String()

  /// Output only. By default, Infra Manager will return a failure when
  /// Terraform encounters a 409 code (resource conflict error) during actuation.
  /// If this flag is set to true, Infra Manager will instead
  /// attempt to automatically import the resource into the Terraform state (for
  /// supported resource types) and continue actuation.
  ///
  /// Not all resource types are supported, refer to documentation.
  public var importExistingResources: Swift.Bool = Swift.Bool()

  /// Output only. The user-specified Cloud Build worker pool resource in which
  /// the Cloud Build job will execute. Format:
  /// `projects/{project}/locations/{location}/workerPools/{workerPoolId}`.
  /// If this field is unspecified, the default Cloud Build worker pool will be
  /// used.
  public var workerPool: Swift.String = Swift.String()

  /// Output only. The user-specified Terraform version constraint.
  /// Example: "=1.3.10".
  public var tfVersionConstraint: Swift.String = Swift.String()

  /// Output only. The version of Terraform used to create the Revision.
  /// It is in the format of "Major.Minor.Patch", for example, "1.3.10".
  public var tfVersion: Swift.String = Swift.String()

  /// Output only. Cloud Storage path containing quota validation results. This
  /// field is set when a user sets Deployment.quota_validation field to ENABLED
  /// or ENFORCED. Format: `gs://{bucket}/{object}`.
  public var quotaValidationResults: Swift.String = Swift.String()

  /// Optional. Input to control quota checks for resources in terraform
  /// configuration files. There are limited resources on which quota validation
  /// applies.
  public var quotaValidation: QuotaValidation = QuotaValidation()

  /// Output only. This field specifies the provider configurations.
  public var providerConfig: ProviderConfig? = nil

  /// Blueprint that was deployed.
  public var blueprint: OneOf_Blueprint? = nil

  /// Initialize a new instance of `Revision`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Revision().with { $0.terraformBlueprint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case terraformBlueprint = "terraformBlueprint"
    case name = "name"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case action = "action"
    case state = "state"
    case applyResults = "applyResults"
    case stateDetail = "stateDetail"
    case errorCode = "errorCode"
    case build = "build"
    case logs = "logs"
    case tfErrors = "tfErrors"
    case errorLogs = "errorLogs"
    case serviceAccount = "serviceAccount"
    case importExistingResources = "importExistingResources"
    case workerPool = "workerPool"
    case tfVersionConstraint = "tfVersionConstraint"
    case tfVersion = "tfVersion"
    case quotaValidationResults = "quotaValidationResults"
    case quotaValidation = "quotaValidation"
    case providerConfig = "providerConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.action = try container.decode(Revision.Action.self, forKey: .action)
    self.state = try container.decode(Revision.State.self, forKey: .state)
    self.applyResults = try container.decodeIfPresent(ApplyResults.self, forKey: .applyResults)
    self.stateDetail = try container.decode(Swift.String.self, forKey: .stateDetail)
    self.errorCode = try container.decode(Revision.ErrorCode.self, forKey: .errorCode)
    self.build = try container.decode(Swift.String.self, forKey: .build)
    self.logs = try container.decode(Swift.String.self, forKey: .logs)
    self.tfErrors = try container.decode([TerraformError].self, forKey: .tfErrors)
    self.errorLogs = try container.decode(Swift.String.self, forKey: .errorLogs)
    self.serviceAccount = try container.decode(Swift.String.self, forKey: .serviceAccount)
    self.importExistingResources = try container.decode(
      Swift.Bool.self, forKey: .importExistingResources)
    self.workerPool = try container.decode(Swift.String.self, forKey: .workerPool)
    self.tfVersionConstraint = try container.decode(Swift.String.self, forKey: .tfVersionConstraint)
    self.tfVersion = try container.decode(Swift.String.self, forKey: .tfVersion)
    self.quotaValidationResults = try container.decode(
      Swift.String.self, forKey: .quotaValidationResults)
    self.quotaValidation = try container.decode(QuotaValidation.self, forKey: .quotaValidation)
    self.providerConfig = try container.decodeIfPresent(
      ProviderConfig.self, forKey: .providerConfig)

    var blueprint: OneOf_Blueprint? = nil
    let blueprintCheckAndSet = {
      if blueprint != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'blueprint'"))
      }
      blueprint = $0
    }
    if let terraformBlueprint = try container.decodeIfPresent(
      TerraformBlueprint?.self, forKey: .terraformBlueprint)
    {
      try blueprintCheckAndSet(.terraformBlueprint(terraformBlueprint))
    }
    self.blueprint = blueprint
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.action, forKey: .action)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.applyResults, forKey: .applyResults)
    try container.encode(self.stateDetail, forKey: .stateDetail)
    try container.encode(self.errorCode, forKey: .errorCode)
    try container.encode(self.build, forKey: .build)
    try container.encode(self.logs, forKey: .logs)
    try container.encode(self.tfErrors, forKey: .tfErrors)
    try container.encode(self.errorLogs, forKey: .errorLogs)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.importExistingResources, forKey: .importExistingResources)
    try container.encode(self.workerPool, forKey: .workerPool)
    try container.encode(self.tfVersionConstraint, forKey: .tfVersionConstraint)
    try container.encode(self.tfVersion, forKey: .tfVersion)
    try container.encode(self.quotaValidationResults, forKey: .quotaValidationResults)
    try container.encode(self.quotaValidation, forKey: .quotaValidation)
    try container.encode(self.providerConfig, forKey: .providerConfig)

    if let choice = self.blueprint {
      switch choice {
      case .terraformBlueprint(let value):
        try container.encode(value, forKey: .terraformBlueprint)
      }
    }
  }

  /// Actions that generate a revision.
  public enum Action: Codable, Equatable, Sendable {
    /// The default value. This value is used if the action is omitted.
    case unspecified
    /// The revision was generated by creating a deployment.
    case create
    /// The revision was generated by updating a deployment.
    case update
    /// The revision was deleted.
    case delete
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .create: return 1
      case .update: return 2
      case .delete: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ACTION_UNSPECIFIED"
      case .create: return "CREATE"
      case .update: return "UPDATE"
      case .delete: return "DELETE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ACTION_UNSPECIFIED": self = .unspecified
      case "CREATE": self = .create
      case "UPDATE": self = .update
      case "DELETE": self = .delete
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .create
      case 2: self = .update
      case 3: self = .delete
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .create: return try container.encode(1)
      case .update: return try container.encode(2)
      case .delete: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible states of a revision.
  public enum State: Codable, Equatable, Sendable {
    /// The default value. This value is used if the state is omitted.
    case unspecified
    /// The revision is being applied.
    case applying
    /// The revision was applied successfully.
    case applied
    /// The revision could not be applied successfully.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .applying: return 1
      case .applied: return 2
      case .failed: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .applying: return "APPLYING"
      case .applied: return "APPLIED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "APPLYING": self = .applying
      case "APPLIED": self = .applied
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .applying
      case 2: self = .applied
      case 3: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .applying: return try container.encode(1)
      case .applied: return try container.encode(2)
      case .failed: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible errors if Revision could not be created or updated successfully.
  public enum ErrorCode: Codable, Equatable, Sendable {
    /// No error code was specified.
    case unspecified
    /// Cloud Build failed due to a permission issue.
    case cloudBuildPermissionDenied
    /// Cloud Build job associated with creating or updating a deployment could
    /// not be started.
    case applyBuildApiFailed
    /// Cloud Build job associated with creating or updating a deployment was
    /// started but failed.
    case applyBuildRunFailed
    /// quota validation failed for one or more resources in terraform
    /// configuration files.
    case quotaValidationFailed
    /// Failed to import values from an external source.
    case externalValueSourceImportFailed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cloudBuildPermissionDenied: return 1
      case .applyBuildApiFailed: return 4
      case .applyBuildRunFailed: return 5
      case .quotaValidationFailed: return 7
      case .externalValueSourceImportFailed: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ERROR_CODE_UNSPECIFIED"
      case .cloudBuildPermissionDenied: return "CLOUD_BUILD_PERMISSION_DENIED"
      case .applyBuildApiFailed: return "APPLY_BUILD_API_FAILED"
      case .applyBuildRunFailed: return "APPLY_BUILD_RUN_FAILED"
      case .quotaValidationFailed: return "QUOTA_VALIDATION_FAILED"
      case .externalValueSourceImportFailed: return "EXTERNAL_VALUE_SOURCE_IMPORT_FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ERROR_CODE_UNSPECIFIED": self = .unspecified
      case "CLOUD_BUILD_PERMISSION_DENIED": self = .cloudBuildPermissionDenied
      case "APPLY_BUILD_API_FAILED": self = .applyBuildApiFailed
      case "APPLY_BUILD_RUN_FAILED": self = .applyBuildRunFailed
      case "QUOTA_VALIDATION_FAILED": self = .quotaValidationFailed
      case "EXTERNAL_VALUE_SOURCE_IMPORT_FAILED": self = .externalValueSourceImportFailed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cloudBuildPermissionDenied
      case 4: self = .applyBuildApiFailed
      case 5: self = .applyBuildRunFailed
      case 7: self = .quotaValidationFailed
      case 8: self = .externalValueSourceImportFailed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .cloudBuildPermissionDenied: return try container.encode(1)
      case .applyBuildApiFailed: return try container.encode(4)
      case .applyBuildRunFailed: return try container.encode(5)
      case .quotaValidationFailed: return try container.encode(7)
      case .externalValueSourceImportFailed: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Blueprint that was deployed.
  public enum OneOf_Blueprint: Codable, Equatable, Sendable {
    /// Output only. A blueprint described using Terraform's HashiCorp
    /// Configuration Language as a root module.
    indirect case terraformBlueprint(TerraformBlueprint?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.Revision"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
