// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleRpc

/// Errors encountered during actuation using Terraform
public struct TerraformError: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Address of the resource associated with the error,
  /// e.g. `google_compute_network.vpc_network`.
  public var resourceAddress: Swift.String = Swift.String()

  /// HTTP response code returned from Google Cloud Platform APIs when Terraform
  /// fails to provision the resource. If unset or 0, no HTTP response code was
  /// returned by Terraform.
  public var httpResponseCode: Swift.Int32 = Swift.Int32()

  /// A human-readable error description.
  public var errorDescription: Swift.String = Swift.String()

  /// Output only. Original error response from underlying Google API, if
  /// available.
  public var error: GoogleRpc.Status? = nil

  /// Initialize a new instance of `TerraformError`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TerraformError().with { $0.resourceAddress = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.TerraformError"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
