// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// TerraformBlueprint describes the source of a Terraform root module which
/// describes the resources and configs to be deployed.
public struct TerraformBlueprint: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Input variable values for the Terraform blueprint.
  public var inputValues: [Swift.String: TerraformVariable] = [:]

  /// Optional. Map of input variable names in this blueprint to configurations
  /// for importing values from external sources.
  public var externalValues: [Swift.String: ExternalValueSource] = [:]

  /// Location of the source configs.
  /// Required.
  public var source: OneOf_Source? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TerraformBlueprint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TerraformBlueprint().with { $0.gcsSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcsSource = CodingKeys(stringValue: "gcsSource")
    static let gitSource = CodingKeys(stringValue: "gitSource")
    static let inputValues = CodingKeys(stringValue: "inputValues")
    static let externalValues = CodingKeys(stringValue: "externalValues")

    static let _knownKeys: Set<Swift.String> = [
      "gcsSource",
      "gitSource",
      "inputValues",
      "externalValues",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [Swift.String: TerraformVariable].self, forKey: .inputValues)
    {
      self.inputValues = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: ExternalValueSource].self, forKey: .externalValues)
    {
      self.externalValues = value
    }

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let gcsSource = try container.decodeIfPresent(Swift.String.self, forKey: .gcsSource) {
      try sourceCheckAndSet(.gcsSource(gcsSource))
    }
    if let gitSource = try container.decodeIfPresent(GitSource?.self, forKey: .gitSource) {
      try sourceCheckAndSet(.gitSource(gitSource))
    }
    self.source = source
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.inputValues, forKey: .inputValues)
    try container.encode(self.externalValues, forKey: .externalValues)

    if let choice = self.source {
      switch choice {
      case .gcsSource(let value):
        try container.encode(value, forKey: .gcsSource)
      case .gitSource(let value):
        try container.encode(value, forKey: .gitSource)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Location of the source configs.
  /// Required.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// URI of an object in Google Cloud Storage.
    /// Format: `gs://{bucket}/{object}`
    ///
    /// URI may also specify an object version for zipped objects.
    /// Format: `gs://{bucket}/{object}#{version}`
    case gcsSource(Swift.String)
    /// URI of a public Git repo.
    indirect case gitSource(GitSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.TerraformBlueprint"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
