// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleWKT

/// Errors encountered during actuation using Terraform
public struct TerraformError: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Address of the resource associated with the error,
  /// e.g. `google_compute_network.vpc_network`.
  public var resourceAddress: Swift.String = Swift.String()

  /// HTTP response code returned from Google Cloud Platform APIs when Terraform
  /// fails to provision the resource. If unset or 0, no HTTP response code was
  /// returned by Terraform.
  public var httpResponseCode: Swift.Int32 = Swift.Int32()

  /// A human-readable error description.
  public var errorDescription: Swift.String = Swift.String()

  /// Output only. Original error response from underlying Google API, if
  /// available.
  public var error: GoogleRpc.Status? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TerraformError`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TerraformError().with { $0.resourceAddress = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let resourceAddress = CodingKeys(stringValue: "resourceAddress")
    static let httpResponseCode = CodingKeys(stringValue: "httpResponseCode")
    static let errorDescription = CodingKeys(stringValue: "errorDescription")
    static let error = CodingKeys(stringValue: "error")

    static let _knownKeys: Set<Swift.String> = [
      "resourceAddress",
      "httpResponseCode",
      "errorDescription",
      "error",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceAddress) {
      self.resourceAddress = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .httpResponseCode) {
      self.httpResponseCode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .errorDescription) {
      self.errorDescription = value
    }
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.resourceAddress, forKey: .resourceAddress)
    try container.encode(self.httpResponseCode, forKey: .httpResponseCode)
    try container.encode(self.errorDescription, forKey: .errorDescription)
    try container.encodeIfPresent(self.error, forKey: .error)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.config.v1.TerraformError"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
